#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Committer sidecar
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: sidecar/teardown

- name: Remove Fabric-X Committer sidecar binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: bin/rm
  when:
    - committer_use_bin

- name: Remove Fabric-X Committer sidecar configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: config/rm

- name: Remove Fabric-X Committer sidecar crypto material
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: crypto/rm
