#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Client TLS crypto material (only when the sidecar requires mTLS)
# =========================
- name: Prepare the Block Explorer client TLS crypto material
  when:
    - hostvars[sidecar_host].committer_use_mtls is defined
    - hostvars[sidecar_host].committer_use_mtls
  block:
    # =========================
    # With OpenSSL
    # =========================
    - name: Generate the Block Explorer client TLS crypto material with OpenSSL
      ansible.builtin.include_role:
        name: hyperledger.fabricx.block_explorer
        tasks_from: crypto/openssl/generate_cert
      when:
        - organization is not defined or (organization is defined and organization.role is undefined)
    # =========================
    # With cryptogen / Fabric-CA (peer organization)
    # =========================
    - name: Prepare the client TLS crypto material for a peer organization
      when:
        - organization is defined
        - organization.role is defined
        - organization.role == 'peer'
      block:
        # =========================
        # With cryptogen
        # =========================
        # If no Fabric CA is defined, assume the crypto material is generated
        # with cryptogen. Thus, transfer it.
        - name: Transfer the Block Explorer client TLS crypto material generated by cryptogen
          ansible.builtin.include_role:
            name: hyperledger.fabricx.block_explorer
            tasks_from: crypto/cryptogen/transfer
          when:
            - organization.fabric_ca_host is not defined
        # =========================
        # With Fabric-CA
        # =========================
        - name: Enroll Block Explorer with Fabric-CA to generate the client TLS crypto material
          ansible.builtin.include_role:
            name: hyperledger.fabricx.block_explorer
            tasks_from: crypto/fabric_ca/enroll
          when:
            - organization.fabric_ca_host is defined

# =========================
# Kubernetes
# =========================
- name: Transfer Block Explorer Kubernetes crypto
  ansible.builtin.include_role:
    name: hyperledger.fabricx.block_explorer
    tasks_from: k8s/crypto/transfer
  when:
    - block_explorer_use_k8s or block_explorer_use_openshift
