#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Resolve effective loadgen address
  vars:
    loadgen_host: "{{ inventory_hostname }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: effective_address

- name: Get Fabric-X Loadgen metrics
  ansible.builtin.uri:
    url: "{{ loadgen_effective_metrics_address }}/metrics"
    validate_certs: false
    method: GET
    return_content: true
  register: loadgen_metrics

- name: Print Fabric-X Loadgen metrics
  ansible.builtin.debug:
    msg: "{{ loadgen_metrics.content }}"
  when:
    - not loadgen_assert_metrics

- name: Set the committed transaction count from Fabric-X Loadgen metrics
  ansible.builtin.set_fact:
    loadgen_tx_committed: >-
      {{
        loadgen_metrics.content
        | regex_findall('loadgen_transaction_committed_total\s+([0-9]+)')
        | default(['0'])
        | first
        | int
      }}
  when:
    - loadgen_assert_metrics

- name: Set the aborted transaction count from Fabric-X Loadgen metrics
  ansible.builtin.set_fact:
    loadgen_tx_aborted: >-
      {{
        loadgen_metrics.content
        | regex_findall('loadgen_transaction_aborted_total\s+([0-9]+)')
        | default(['0'])
        | first
        | int
      }}
  when:
    - loadgen_assert_metrics

- name: Assert the Fabric-X Loadgen committed transaction metric
  ansible.builtin.debug:
    msg:
      - "Transactions committed (>0): {{ loadgen_tx_committed }}"
      - "Transactions aborted: {{ loadgen_tx_aborted }}"
  when:
    - loadgen_assert_metrics
    - loadgen_tx_committed != 0

- name: Fail if no transactions committed
  ansible.builtin.fail:
    msg: "No transactions committed: {{ loadgen_tx_committed }}; transactions aborted: {{ loadgen_tx_aborted }}"
  when:
    - loadgen_assert_metrics
    - loadgen_tx_committed == 0
