#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Set effective loadgen metrics port (NodePort)
  ansible.builtin.set_fact:
    loadgen_k8s_effective_metrics_port: "{{ loadgen_k8s_metrics_node_port }}"
  when:
    - loadgen_use_k8s
    - loadgen_k8s_use_node_port
    - loadgen_k8s_metrics_node_port is defined

- name: Get Fabric-X Loadgen metrics
  vars:
    loadgen_effective_metrics_port: "{{ loadgen_k8s_effective_metrics_port | default(loadgen_metrics_port) }}"
  ansible.builtin.uri:
    url: "{{ loadgen_monitoring_http_protocol }}://{{ actual_host }}:{{ loadgen_effective_metrics_port }}/metrics"
    validate_certs: false
    method: GET
    return_content: true
  register: loadgen_metrics

- name: Print Fabric-X Loadgen metrics
  ansible.builtin.debug:
    msg: "{{ loadgen_metrics.content }}"
  when:
    - not loadgen_assert_metrics

- name: Set the transaction latency from the Fabric-X Loadgen metrics
  ansible.builtin.set_fact:
    loadgen_tx_latency: >-
      {{
        loadgen_metrics.content
        | regex_findall('loadgen_valid_transaction_latency_seconds_count\s+([0-9]+)')
        | default(['0'])
        | first
        | int
      }}
  when:
    - loadgen_assert_metrics

- name: Assert the Fabric-X Loadgen latency metric
  ansible.builtin.debug:
    msg: "The transaction latency is valid (>0): {{ loadgen_tx_latency }}"
  when:
    - loadgen_assert_metrics
    - loadgen_tx_latency != 0

- name: Assert the Fabric-X Loadgen latency metric
  ansible.builtin.fail:
    msg: "The transaction latency is invalid: {{ loadgen_tx_latency }}"
  when:
    - loadgen_assert_metrics
    - loadgen_tx_latency == 0
