#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Set effective loadgen limit-rate endpoint as k8s NodePort
  ansible.builtin.set_fact:
    loadgen_limit_rate_endpoint: "http://{{ actual_host }}:{{ loadgen_k8s_web_node_port }}/setRateLimit"
  when:
    - loadgen_use_k8s
    - loadgen_k8s_web_node_port is defined
    - loadgen_k8s_loadbalancer_expose_web_port is not defined
      or not loadgen_k8s_loadbalancer_expose_web_port

- name: Send HTTP POST request to set the new limit
  vars:
    loadgen_default_limit_rate_endpoint: "http://{{ actual_host }}:{{ loadgen_web_port }}/setRateLimit"
    loadgen_effective_limit_rate_endpoint: "{{ loadgen_limit_rate_endpoint | default(loadgen_default_limit_rate_endpoint) }}"
  ansible.builtin.uri:
    url: "{{ loadgen_effective_limit_rate_endpoint }}"
    validate_certs: false
    method: POST
    body_format: json
    body: >-
      {{
        {
          'rate': loadgen_limit_rate | int
        }
      }}
    status_code: 200
