#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Resolve effective loadgen address
  vars:
    loadgen_host: "{{ inventory_hostname }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: effective_address

- name: Send HTTP POST request to set the new limit
  vars:
    loadgen_effective_limit_rate_endpoint: "{{ loadgen_effective_web_address }}/setRateLimit"
  ansible.builtin.uri:
    url: "{{ loadgen_effective_limit_rate_endpoint }}"
    validate_certs: false
    method: POST
    body_format: json
    body: >-
      {{
        {
          'rate': loadgen_limit_rate | int
        }
      }}
    status_code: 200
