#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Endorse the Fabric-X ConfigUpdate
  vars:
    bin_command: >-
      {{ fxadmin_bin_name }} tx
      endorse
      {{ fxadmin_output_dir }}/config_update.pb
      --config={{ fxadmin_remote_config_dir }}/{{ fxadmin_config_file }}
      --output={{ fxadmin_output }}
    bin_run_with_tmux: false
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
