#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Submit the Fabric-X transaction
  vars:
    bin_command: >-
      {{ fxadmin_bin_name }} tx
      submit
      {{ fxadmin_output_dir }}/config_tx.pb
      --config={{ fxadmin_remote_config_dir }}/{{ fxadmin_config_file }}
      --current-block={{ fxadmin_output_dir }}/current_block.pb
    bin_run_with_tmux: false
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
