#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Committer coordinator Kubernetes workload
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: coordinator/k8s/teardown

- name: Remove Fabric-X Committer coordinator ConfigMap
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/config/rm

- name: Remove Fabric-X Committer coordinator Secret
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/crypto/rm
