#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Namespace
# =========================
- name: Ensure Kubernetes namespace exists for Fabric-X Committer sidecar
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: namespace/create

# =========================
# Generate config on controller
# =========================
- name: Generate Hyperledger Fabric-X Committer sidecar config on controller
  vars:
    orderer_assembler_ref_host: >-
      {{
        orderer_assemblers
        | first
      }}
  ansible.builtin.template:
    src: "config-sidecar.yaml.j2"
    dest: "{{ committer_remote_config_dir }}/{{ committer_config_file }}"
    mode: "0o644"

# =========================
# Apply ConfigMap
# =========================
- name: Apply Fabric-X Committer sidecar ConfigMap
  vars:
    committer_k8s_coordinator_ca_path: "{{ fetched_artifacts_dir }}/{{ committer_coordinator }}/tls/ca.crt"
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/configmap-sidecar.yaml.j2
