#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =======================
# container
# =======================
- name: Check that the EVM JSON-RPC port is open
  vars:
    utils_ports_to_ping:
      - "{{ evm_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when: not (evm_use_k8s or evm_use_openshift)

- name: Check the EVM JSON-RPC endpoint
  vars:
    evm_ping_base_url: "http://{{ actual_host }}:{{ evm_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.evm
    tasks_from: rpc_check
  when: not (evm_use_k8s or evm_use_openshift)

# =======================
# k8s
# =======================
- name: Check that the EVM Kubernetes services are reachable
  ansible.builtin.include_role:
    name: hyperledger.fabricx.evm
    tasks_from: k8s/ping
  when: evm_use_k8s

# =======================
# openshift
# =======================
- name: Check that the EVM OpenShift route and Kubernetes services are open
  ansible.builtin.include_role:
    name: hyperledger.fabricx.evm
    tasks_from: openshift/ping
  when: evm_use_openshift
