{
 "title": "Arma Dashboard",
 "description": "running commands were for 3 days :\n\nfor i in {1..4}; do\n  nohup ./armageddon receive \\\n    --config=arma-config/config/party${i}/user_config.yaml \\\n    --pullFromPartyId=${i} \\\n    --expectedTxs=259200000 \\\n    --output=\"/tmp${i}\" \\\n    >> receiver${i}.log 2>&1 &\ndone\nnohup ./armageddon load --config=arma-config/config/party1/user_config.yaml --transactions=259200000 --rate=1000 --txSize=300 >> loader.log 2>&1 &",
 "tags": [ "Arma Nightly" ],
 "time": { "from": "2026-01-29T09:00:00.000Z", "to": "2026-02-01T10:00:00.000Z" },
 "panels": [
  { "title": "Batchers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Batcher - Incoming TXs / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(batcher_router_txs_total[1m])",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - TXs Batched / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(batcher_batched_txs_total[1m])",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "batcher_mempool_size",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - Batches Created / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(batcher_batches_created_total[1m])",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - Current Role",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "batcher_current_role",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - Role Changes / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(batcher_role_changes_total[30m])",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - Complaints / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(batcher_complaints_total[30m])",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  {
   "title": "Batcher - First Resend / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(batcher_first_resends_total[30m])",
     "legendFormat": "Batcher {{party_id}}-{{shard_id}}"
    }
   ]
  },
  { "title": "Consenters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Consenter - Decisions / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(consensus_decisions_count[1m])",
     "legendFormat": "Consenter {{party_id}}"
    }
   ]
  },
  {
   "title": "Consenter - Blocks / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(consensus_blocks_count[1m])",
     "legendFormat": "Consenter {{party_id}}"
    }
   ]
  },
  {
   "title": "Consenter - BAFs / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "rate(consensus_bafs_count[1m])", "legendFormat": "Consenter {{party_id}}" }
   ]
  },
  {
   "title": "Consenter - Complaints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(consensus_complaints_count[30m])",
     "legendFormat": "Consenter {{party_id}}"
    }
   ]
  },
  { "title": "Routers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Router - Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(router_requests_completed[1m])",
     "legendFormat": "Router {{party_id}}"
    }
   ]
  },
  {
   "title": "Router - Rejected Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(router_requests_rejected{code=\"400\"}[1m])",
     "legendFormat": "Router {{party_id}} - 400"
    },
    {
     "expr": "rate(router_requests_rejected{code=\"500\"}[1m])",
     "legendFormat": "Router {{party_id}} - 500"
    }
   ]
  },
  {
   "title": "Router - Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(router_requests_completed[1m])",
     "legendFormat": "Router {{party_id}}"
    }
   ]
  },
  { "title": "Assemblers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Assembler - TX per Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "rate(assembler_ledger_transaction_count_total[1m])\r\n/\r\nrate(assembler_ledger_blocks_count_total[1m])\r\n",
     "legendFormat": "Assembler {{party_id}}"
    }
   ]
  },
  {
   "title": "Assembler - Blocks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "rate(assembler_ledger_blocks_count_total[1m])",
     "legendFormat": "Assembler {{party_id}}"
    }
   ]
  },
  {
   "title": "Assembler  - TX/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "rate(assembler_ledger_transaction_count_total[1m])",
     "legendFormat": "Assembler {{party_id}}"
    }
   ]
  }
 ]
}