#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Fabric-X Orderer config directory
  ansible.builtin.file:
    path: "{{ orderer_remote_config_dir }}"
    state: absent
  when: not orderer_use_k8s

- name: Remove Fabric-X Orderer K8s config
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: k8s/config/rm
  when: orderer_use_k8s
