#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Grafana container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.grafana
    tasks_from: container/start
  when: grafana_use_container

- name: Start Grafana on Kubernetes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.grafana
    tasks_from: k8s/start
  when: grafana_use_k8s

- name: Start Grafana on OpenShift
  ansible.builtin.include_role:
    name: hyperledger.fabricx.grafana
    tasks_from: openshift/start
  when: grafana_use_openshift
