#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Run {{ fx_reconfig_client_bin_name }} broadcast
  vars:
    bin_run_with_tmux: false
    bin_remote_dir: "{{ cli_bin_dir }}"
    bin_command: >-
      {{ fx_reconfig_client_bin_name }} broadcast
      --envelope {{ fx_reconfig_client_envelope_file }}
      --endpoints {{ fx_reconfig_client_router_endpoints | join(',') }}
      --quorum {{ fx_reconfig_client_quorum }}
      {% if fx_reconfig_client_tls_ca %}--tls-ca {{ fx_reconfig_client_tls_ca }}{% endif %}
      {% if fx_reconfig_client_tls_client_cert %}--tls-client-cert {{ fx_reconfig_client_tls_client_cert }}{% endif %}
      {% if fx_reconfig_client_tls_client_key %}--tls-client-key {{ fx_reconfig_client_tls_client_key }}{% endif %}
      {% if fx_reconfig_client_tls_server_name %}--tls-server-name {{ fx_reconfig_client_tls_server_name }}{% endif %}
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
