#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Semaphore UI binary
  vars:
    bin_name: "{{ semaphore_ui_bin_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: rm
