#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Jaeger Image
# =========================
jaeger_registry_endpoint: "{{ lookup('env', 'JAEGER_REGISTRY_ENDPOINT') or 'docker.io/jaegertracing' }}"
jaeger_image_name: "all-in-one"
jaeger_image_tag: "latest"
jaeger_image: "{{ jaeger_registry_endpoint }}/{{ jaeger_image_name }}:{{ jaeger_image_tag }}"
jaeger_container_name: "{{ inventory_hostname }}"

# =========================
# Paths/Locations
# =========================
jaeger_remote_config_dir: "{{ remote_config_dir }}"
jaeger_container_config_dir: "/var/config"

# =========================
# Jaeger Default Ports
# =========================
jaeger_ui_port: 16686
jaeger_admin_port: 14269
jaeger_http_server_port: 14268
jaeger_http_collector_port: 4318
jaeger_grpc_server_port: 14250
jaeger_collector_port: 4317

# =========================
# Deployment Mode
# =========================
jaeger_use_k8s: false
jaeger_use_container: "{{ not jaeger_use_k8s }}"

# =========================
# Kubernetes
# =========================
jaeger_k8s_resource_name: "{{ inventory_hostname }}"
jaeger_k8s_wait_timeout: 120
jaeger_k8s_fs_group: 0

jaeger_k8s_ui_node_port: "{{ jaeger_ui_port }}"
jaeger_k8s_admin_node_port: "{{ jaeger_admin_port }}"
jaeger_k8s_http_server_node_port: "{{ jaeger_http_server_port }}"
jaeger_k8s_http_collector_node_port: "{{ jaeger_http_collector_port }}"
jaeger_k8s_grpc_server_node_port: "{{ jaeger_grpc_server_port }}"
jaeger_k8s_collector_node_port: "{{ jaeger_collector_port }}"
