#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch Fabric CA server crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.fabric_ca_server.fetch_crypto

- name: Fetch Hyperledger Fabric-X Orderer crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.fetch_crypto

- name: Fetch Hyperledger Fabric-X Committer crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.fetch_crypto

- name: Fetch Hyperledger Fabric-X Loadgen crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.loadgen.fetch_crypto

- name: Fetch Monitoring crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.monitoring.fetch_crypto
