#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Grafana TLS directory
  ansible.builtin.file:
    path: "{{ grafana_remote_config_dir }}/tls"
    state: absent
  when:
    - grafana_use_tls

- name: Delete Grafana Kubernetes Secret
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: "{{ grafana_k8s_resource_name }}"
    namespace: "{{ k8s_namespace }}"
  when: grafana_use_k8s
