#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check that the Block Explorer UI web node port is open
  vars:
    utils_ports_to_ping:
      - "{{ block_explorer_ui_k8s_node_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when:
    - block_explorer_ui_k8s_node_port is defined

- name: Check that the Block Explorer UI web load balancer port is open
  vars:
    utils_ports_to_ping:
      - "{{ block_explorer_ui_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when:
    - block_explorer_ui_k8s_loadbalancer_expose_port
