#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Generate the Fabric-X Committer crypto material
  hosts: "{{ target_hosts | default('fabric_x_committers') }}:&fabric_x_committers"
  tasks:
    # =========================
    # HLFX Committer
    # =========================
    - name: Setup Hyperledger Fabric-X Committer crypto material
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: crypto/setup
      when:
        - committer_component_type is defined
    - name: Fetch Hyperledger Fabric-X Committer certificates
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: crypto/fetch
      when:
        - committer_component_type is defined
