#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown the Fabric-X Committer
  hosts: "{{ target_hosts | default('fabric_x_committers') }}:&fabric_x_committers"
  tasks:
    # =========================
    # HLFX Committer
    # =========================
    - name: Teardown the Fabric-X Committer services
      vars:
        reference_committer_hosts: >-
          {{
            (
              groups['fabric_x_committers']
              | map('extract', hostvars)
              | selectattr('organization', 'defined')
              | selectattr('organization.domain', 'defined')
              | selectattr('organization.domain', '==', organization.domain)
              | map(attribute='inventory_hostname')
              | list
            )
            or groups['fabric_x_committers']
          }}
        committer_validators: >-
          {{
            reference_committer_hosts
            | map('extract', hostvars)
            | selectattr('committer_component_type', 'defined')
            | selectattr('committer_component_type', '==', 'validator')
            | map(attribute='inventory_hostname')
            | sort
            | list
          }}
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: teardown
      when:
        - committer_component_type is defined
