#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

all:
  vars:
    # =========================
    # Organizations
    # =========================
    organizations:
      orderer_org_1: &OrdererOrg1
        name: OrdererOrg1
        domain: ordererorg1.example.com
      orderer_org_2: &OrdererOrg2
        name: OrdererOrg2
        domain: ordererorg2.example.com
      orderer_org_3: &OrdererOrg3
        name: OrdererOrg3
        domain: ordererorg3.example.com
      orderer_org_4: &OrdererOrg4
        name: OrdererOrg4
        domain: ordererorg4.example.com
  children:
    fabric_x_orderers:
      vars:
        # -------------------------------------------------------
        # Orderer deployment mode
        # -------------------------------------------------------
        orderer_use_tls: true
        orderer_use_mtls: true
        orderer_use_k8s: true
      children:
        fabric_x_orderer_1:
          vars:
            organization:
              <<: *OrdererOrg1
              role: orderer
              orderer:
                name: "{{ inventory_hostname }}"
            orderer_group: 1
          hosts:
            orderer-router-1:
              orderer_component_type: router
              orderer_rpc_port: 30050
              orderer_metrics_port: 30060
            orderer-consenter-1:
              orderer_component_type: consenter
              orderer_rpc_port: 30051
              orderer_metrics_port: 30061
            orderer-assembler-1:
              orderer_component_type: assembler
              orderer_rpc_port: 30052
              orderer_metrics_port: 30062
            orderer-batcher-1:
              orderer_component_type: batcher
              orderer_shard_id: 1
              orderer_rpc_port: 30053
              orderer_metrics_port: 30063
        fabric_x_orderer_2:
          vars:
            organization:
              <<: *OrdererOrg2
              role: orderer
              orderer:
                name: "{{ inventory_hostname }}"
            orderer_group: 2
          hosts:
            orderer-router-2:
              orderer_component_type: router
              orderer_rpc_port: 30150
              orderer_metrics_port: 30160
            orderer-consenter-2:
              orderer_component_type: consenter
              orderer_rpc_port: 30151
              orderer_metrics_port: 30161
            orderer-assembler-2:
              orderer_component_type: assembler
              orderer_rpc_port: 30152
              orderer_metrics_port: 30162
            orderer-batcher-2:
              orderer_component_type: batcher
              orderer_shard_id: 1
              orderer_rpc_port: 30153
              orderer_metrics_port: 30163
        fabric_x_orderer_3:
          vars:
            organization:
              <<: *OrdererOrg3
              role: orderer
              orderer:
                name: "{{ inventory_hostname }}"
            orderer_group: 3
          hosts:
            orderer-router-3:
              orderer_component_type: router
              orderer_rpc_port: 30250
              orderer_metrics_port: 30260
            orderer-consenter-3:
              orderer_component_type: consenter
              orderer_rpc_port: 30251
              orderer_metrics_port: 30261
            orderer-assembler-3:
              orderer_component_type: assembler
              orderer_rpc_port: 30252
              orderer_metrics_port: 30262
            orderer-batcher-3:
              orderer_component_type: batcher
              orderer_shard_id: 1
              orderer_rpc_port: 30253
              orderer_metrics_port: 30263
        fabric_x_orderer_4:
          vars:
            organization:
              <<: *OrdererOrg4
              role: orderer
              orderer:
                name: "{{ inventory_hostname }}"
            orderer_group: 4
          hosts:
            orderer-router-4:
              orderer_component_type: router
              orderer_rpc_port: 30350
              orderer_metrics_port: 30360
            orderer-consenter-4:
              orderer_component_type: consenter
              orderer_rpc_port: 30351
              orderer_metrics_port: 30361
            orderer-assembler-4:
              orderer_component_type: assembler
              orderer_rpc_port: 30352
              orderer_metrics_port: 30362
            orderer-batcher-4:
              orderer_component_type: batcher
              orderer_shard_id: 1
              orderer_rpc_port: 30353
              orderer_metrics_port: 30363
