#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Fabric-X Loadgen image
# =========================
loadgen_registry_endpoint: "{{ lookup('env', 'LOADGEN_REGISTRY_ENDPOINT') or 'docker.io/hyperledger' }}"
loadgen_image_name: "fabric-x-loadgen"
loadgen_image_tag: "0.1.7"
loadgen_image: "{{ loadgen_registry_endpoint }}/{{ loadgen_image_name }}:{{ loadgen_image_tag }}"
loadgen_container_name: "{{ inventory_hostname }}"

# =========================
# Fabric-X Loadgen bin
# =========================
loadgen_git_uri: "https://github.com/hyperledger/fabric-x-committer.git"
loadgen_git_commit: "v0.1.7"
loadgen_source_code_package: "cmd/loadgen"
loadgen_bin_package: "github.com/hyperledger/fabric-x-committer/cmd/loadgen"
loadgen_bin_name: "loadgen"
loadgen_use_bin: false

# =========================
# Paths/Locations
# =========================
loadgen_remote_config_dir: "{{ remote_config_dir }}"
loadgen_container_config_dir: "/config"
loadgen_config_file: "config-loadgen.yaml"
loadgen_admin_pub_key_file: "admin_pub_key.pem"
loadgen_admin_priv_key_file: "admin_priv_key.pem"

# =========================
# Miscellaneous
# =========================
loadgen_assert_metrics: false

# =========================
# TLS Settings
# =========================
loadgen_use_tls: false

# =========================
# Kubernetes
# =========================
loadgen_use_k8s: false
loadgen_use_container: "{{ (not loadgen_use_bin) and (not loadgen_use_k8s) }}"

loadgen_k8s_resource_name: "{{ inventory_hostname }}"
loadgen_k8s_wait: true
loadgen_k8s_wait_timeout: 120
loadgen_k8s_fs_group: 10001

# NodePort for external access
loadgen_k8s_web_node_port: "{{ loadgen_web_port }}"
loadgen_k8s_metrics_node_port: "{{ loadgen_metrics_port }}"
