#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Block Explorer Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: "{{ block_explorer_k8s_resource_name }}"
    namespace: "{{ k8s_namespace | default('default') }}"

- name: Remove Block Explorer Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: "{{ block_explorer_k8s_resource_name }}"
    namespace: "{{ k8s_namespace | default('default') }}"

- name: Remove Block Explorer NodePort Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: "{{ block_explorer_k8s_resource_name }}-nodeport"
    namespace: "{{ k8s_namespace | default('default') }}"
  when: block_explorer_k8s_node_port is defined

- name: Delete Block Explorer LoadBalancer Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ block_explorer_k8s_resource_name }}-loadbalancer"
    namespace: "{{ k8s_namespace | default('default') }}"
  when: block_explorer_k8s_loadbalancer_expose_port
