#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop the Fabric-X Block Explorer
  hosts: "{{ target_hosts | default('fabric_x_block_explorer') }}:&fabric_x_block_explorer"
  tasks:
    # =========================
    # Block Explorer server and UI
    # =========================
    - name: Stop the Fabric-X Block Explorer server and UI
      ansible.builtin.include_role:
        name: hyperledger.fabricx.block_explorer
        tasks_from: stop
      when:
        - block_explorer_port is defined
    # =========================
    # Postgres
    # =========================
    - name: Stop the Fabric-X Block Explorer Postgres DB
      ansible.builtin.include_role:
        name: hyperledger.fabricx.postgres
        tasks_from: stop
      when:
        - postgres_port is defined
