#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Generate YugabyteDB crypto material
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Setup YugabyteDB node crypto material
      ansible.builtin.include_role:
        name: hyperledger.fabricx.yugabyte
        tasks_from: crypto/setup
      when:
        - yugabyte_component_type is defined
    - name: Fetch YugabyteDB node certificates
      ansible.builtin.include_role:
        name: hyperledger.fabricx.yugabyte
        tasks_from: crypto/fetch
      when:
        - yugabyte_component_type is defined
