#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Generate the Loki TLS crypto material with OpenSSL
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loki
    tasks_from: crypto/openssl/generate_cert
  when:
    - loki_use_tls

- name: Apply Loki K8s crypto Secret
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loki
    tasks_from: k8s/crypto/transfer
  when:
    - loki_use_k8s or loki_use_openshift
