#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Fabric CA image
# =========================
fabric_ca_registry_endpoint: "{{ lookup('env', 'FABRIC_CA_REGISTRY_ENDPOINT') or 'docker.io/hyperledger' }}"
fabric_ca_image_name: "fabric-ca"
fabric_ca_image_tag: "1.5.15"
fabric_ca_image: "{{ fabric_ca_registry_endpoint }}/{{ fabric_ca_image_name }}:{{ fabric_ca_image_tag }}"
fabric_ca_container_name: "{{ inventory_hostname }}"

# =========================
# Fabric CA binaries
# =========================
fabric_ca_git_hub_url: github.com
fabric_ca_git_repo: "hyperledger/fabric-ca"
fabric_ca_git_commit: "v1.5.15"
# Fabric CA Server binary
fabric_ca_server_source_code_package: "cmd/fabric-ca-server"
fabric_ca_server_bin_package: "{{ fabric_ca_git_hub_url }}/{{ fabric_ca_git_repo }}/{{ fabric_ca_server_source_code_package }}"
fabric_ca_server_bin_name: "fabric-ca-server"
fabric_ca_server_use_bin: false
# Fabric CA Client binary
fabric_ca_client_source_code_package: "cmd/fabric-ca-client"
fabric_ca_client_bin_package: "{{ fabric_ca_git_hub_url }}/{{ fabric_ca_git_repo }}/{{ fabric_ca_client_source_code_package }}"
fabric_ca_client_bin_name: "fabric-ca-client"
fabric_ca_client_use_bin: false

# =========================
# Paths, locations
# =========================
fabric_ca_server_remote_config_dir: "{{ remote_config_dir }}"
fabric_ca_server_remote_data_dir: "{{ remote_data_dir }}"
fabric_ca_server_container_config_dir: "/config"
fabric_ca_client_container_config_dir: "/config"
fabric_ca_server_container_data_dir: "/data"
fabric_ca_server_config_dir: "{{ fabric_ca_server_remote_config_dir if fabric_ca_server_use_bin else fabric_ca_server_container_config_dir }}"
fabric_ca_server_data_dir: "{{ fabric_ca_server_remote_data_dir if fabric_ca_server_use_bin else fabric_ca_server_container_data_dir }}"

# =========================
# General settings
# =========================
fabric_ca_log_level: "INFO"

# =========================
# TLS settings
# =========================
fabric_ca_scheme: "{{ 'https' if fabric_ca_use_tls else 'http' }}"
fabric_ca_use_tls: false

# =========================
# CA identity settings
# =========================
fabric_ca_name: "{{ inventory_hostname }}"
fabric_ca_enrollment_type: bccsp # bccsp or idemix
# Signing profile used when enrolling Idemix credentials.
fabric_ca_idemix_enrollment_profile: idemix

# =========================
# CA x509 file settings
# =========================
fabric_ca_server_openssl_curve: "P-256"
fabric_ca_server_ca_private_key_file: "ca-key.pem"
fabric_ca_server_ca_cert_file: "ca-cert.pem"

# =========================
# CA TLS file settings
# =========================
fabric_ca_server_tls_private_key_file: "tls-key.pem"
fabric_ca_server_tls_cert_file: "tls-cert.pem"

# =========================
# CA Idemix file settings
# =========================
fabric_ca_server_idemixgen_output_dir: "{{ fabric_ca_server_remote_config_dir }}/idemixgen-artifacts"

# =========================
# CSR settings
# =========================
fabric_ca_csr_cn: "{{ fabric_ca_name }}"
fabric_ca_csr_hosts:
  - "{{ ansible_host }}"
  - "{{ actual_host }}"
  - "{{ inventory_hostname }}"
fabric_ca_csr_expiry: "131400h"

# =========================
# Cryptogenize settings
# =========================
fabric_ca_cryptogenize_tls_ca_cert_file: ca.crt
fabric_ca_cryptogenize_tls_cert_file: server.crt
fabric_ca_cryptogenize_tls_key_file: server.key
