#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Mint service-account token for automation
  ansible.builtin.command:
    cmd: >-
      oc create token {{ openshift_cluster_service_account_name }}
      -n {{ openshift_cluster_namespace }}
      --duration={{ openshift_cluster_service_account_token_duration }}
  register: openshift_cluster_sa_token
  no_log: true
  changed_when: false

- name: Login to managed OpenShift cluster with service-account token
  ansible.builtin.command:
    cmd: >-
      oc login
      --token={{ openshift_cluster_sa_token.stdout | trim }}
      --server={{ openshift_cluster_login_server }}
  no_log: true
  changed_when: false

- name: Select OpenShift project with service-account token
  ansible.builtin.command:
    cmd: oc project {{ openshift_cluster_namespace }}
  changed_when: false
