#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop PostgreSQL databases
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Stop PostgreSQL database
      ansible.builtin.include_role:
        name: hyperledger.fabricx.postgres
        tasks_from: stop
      when:
        - postgres_port is defined
