#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Fabric-X Orderer image
# =========================
orderer_registry_endpoint: "{{ lookup('env', 'ORDERER_REGISTRY_ENDPOINT') or 'docker.io/hyperledger' }}"
orderer_image_name: "fabric-x-orderer"
orderer_image_tag: "0.0.23"
orderer_image: "{{ orderer_registry_endpoint }}/{{ orderer_image_name }}:{{ orderer_image_tag }}"
orderer_container_name: "{{ inventory_hostname }}"

# =========================
# Fabric-X Orderer bin
# =========================
orderer_git_hub_url: "github.com"
orderer_git_repo: "hyperledger/fabric-x-orderer"
orderer_git_commit: "v0.0.23"
orderer_source_code_package: "cmd/arma"
orderer_bin_package: "{{ orderer_git_hub_url }}/{{ orderer_git_repo }}/{{ orderer_source_code_package }}"
orderer_bin_name: "arma"

# =========================
# Fabric-X Orderer K8s mode
# =========================
orderer_k8s_resource_name: "{{ inventory_hostname }}"
orderer_k8s_wait_timeout: 120
orderer_k8s_fs_group: 10001
orderer_k8s_rpc_node_port: "{{ orderer_rpc_port }}"
orderer_k8s_metrics_node_port: "{{ orderer_metrics_port }}"

# =========================
# Paths/Locations
# =========================
orderer_remote_config_dir: "{{ remote_config_dir }}"
orderer_remote_data_dir: "{{ remote_data_dir }}"
orderer_container_config_dir: "/config"
orderer_container_data_dir: "/data"
orderer_config_dir: "{{ orderer_remote_config_dir if orderer_use_bin else orderer_container_config_dir }}"
orderer_data_dir: "{{ orderer_remote_data_dir if orderer_use_bin else orderer_container_data_dir }}"
orderer_config_file: "node_config.yaml"

# =========================
# Fabric-X Orderer TLS/mTLS
# =========================
orderer_use_tls: false
orderer_use_mtls: false
# Currently the orderer does not enforce TLS on the http endpoint
orderer_http_protocol: http

# =========================
# Fabric-X Orderer Deployment Mode
# =========================
orderer_use_bin: false
orderer_use_k8s: false
orderer_use_container: "{{ (not orderer_use_bin) and (not orderer_use_k8s) }}"
orderer_deployment_mode: "{%- if orderer_use_bin -%}bin{%- elif orderer_use_k8s -%}k8s{%- else -%}container{%- endif -%}"

# =========================
# Miscellaneous
# =========================
orderer_crypto_name: "{{ organization.orderer.name | default(inventory_hostname) }}"
orderer_genesis_block_file: "{{ channel_id }}_block.pb"
