#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Fabric-X Orderer Secret
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: "{{ orderer_k8s_resource_name }}-secret"
    namespace: "{{ k8s_namespace }}"
