#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Fabric-X Orderer binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: bin/stop

- name: Remove Fabric-X Orderer data
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: data/rm
