#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure AWX inventories exist
  awx.awx.inventory:
    name: "{{ current_awx_inventory.name }}"
    organization: "{{ awx_config_organization_name }}"
    description: "{{ current_awx_inventory.description | default(omit) }}"
    state: present
  loop: "{{ awx_config_inventories }}"
  loop_control:
    loop_var: current_awx_inventory
    label: "{{ current_awx_inventory.name }}"

- name: Ensure AWX SCM inventory sources exist
  awx.awx.inventory_source:
    name: "{{ current_awx_inventory.name }}"
    inventory: "{{ current_awx_inventory.name }}"
    organization: "{{ awx_config_organization_name }}"
    source: scm
    source_project: "{{ awx_config_project_name }}"
    source_path: "{{ current_awx_inventory.source_path }}"
    update_on_launch: true
    overwrite: true
    credential: "{{ current_awx_inventory.credential | default(omit) }}"
    state: present
  loop: "{{ awx_config_inventories }}"
  loop_control:
    loop_var: current_awx_inventory
    label: "{{ current_awx_inventory.name }}"
