#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure AWX job templates exist
  awx.awx.job_template:
    name: "{{ current_awx_job_template.name }}"
    organization: "{{ awx_config_organization_name }}"
    project: "{{ awx_config_project_name }}"
    playbook: "{{ current_awx_job_template.playbook }}"
    inventory: "{{ current_awx_job_template.inventory | default(omit) }}"
    extra_vars: "{{ current_awx_job_template.extra_vars | default({}) }}"
    credentials: "{{ current_awx_job_template.credentials | default(omit) }}"
    job_type: run
    ask_inventory_on_launch: true
    ask_variables_on_launch: true
    state: present
  loop: "{{ awx_config_job_templates }}"
  loop_control:
    loop_var: current_awx_job_template
    label: "{{ current_awx_job_template.name }}"
