#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Grafana web OpenShift Route
  vars:
    openshift_route_name: "{{ grafana_k8s_resource_name }}-web"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: grafana_openshift_route is defined

- name: Remove Grafana workload using generic k8s flow
  ansible.builtin.include_role:
    name: hyperledger.fabricx.grafana
    tasks_from: k8s/rm
