#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Build armageddon
  vars:
    # Git vars
    git_uri: "{{ armageddon_git_uri }}"
    git_commit: "{{ armageddon_git_commit }}"
    # Bin vars
    bin_name: "{{ armageddon_bin_name }}"
    bin_build_on_control_node: true
    bin_dir: "{{ cli_bin_dir }}"
    # Go vars
    go_source_code_package: "{{ armageddon_source_code_package }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: go/build
