#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get Grafana ConfigMaps
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ k8s_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ grafana_k8s_resource_name }}"
      - "app.kubernetes.io/component=grafana"
      - "app.kubernetes.io/part-of=monitoring"
  register: grafana_configmaps

- name: Delete Grafana ConfigMaps
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: "{{ current_grafana_configmap.metadata.name }}"
    namespace: "{{ k8s_namespace }}"
  loop: "{{ grafana_configmaps.resources }}"
  loop_control:
    loop_var: current_grafana_configmap
    label: "{{ current_grafana_configmap.metadata.name }}"
  when:
    - grafana_configmaps is defined
