#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Fxconfig image
# =========================
fxconfig_registry_endpoint: "{{ lookup('env', 'FXCONFIG_REGISTRY_ENDPOINT') or 'docker.io/hyperledger' }}"
fxconfig_image_name: "fabric-x-tools"
fxconfig_image_tag: "0.0.15"
fxconfig_image: "{{ fxconfig_registry_endpoint }}/{{ fxconfig_image_name }}:{{ fxconfig_image_tag }}"
fxconfig_container_name: "fxconfig"

# =========================
# Fxconfig binary
# =========================
fxconfig_git_hub_url: "github.com"
fxconfig_git_repo: "hyperledger/fabric-x"
fxconfig_git_commit: "v0.0.15"
fxconfig_source_code_package: "tools/fxconfig"
fxconfig_bin_name: fxconfig
fxconfig_bin_package: "{{ fxconfig_git_hub_url }}/{{ fxconfig_git_repo }}/{{ fxconfig_source_code_package }}"
fxconfig_use_bin: false

# =========================
# Paths/Locations
# =========================
fxconfig_remote_config_dir: "{{ remote_config_dir }}/fxconfig"
fxconfig_container_config_dir: "/config"
fxconfig_config_file: fxconfig.yaml
fxconfig_output: "{{ fxconfig_remote_config_dir }}/tx.json"

# =========================
# Fxconfig logs
# =========================
fxconfig_log_level: info
fxconfig_log_format: "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"

# =========================
# Fxconfig mTLS settings
# =========================
fxconfig_mtls_client_cert_path: "{{ remote_config_dir }}/tls/server.crt"
fxconfig_mtls_client_key_path: "{{ remote_config_dir }}/tls/server.key"

# =========================
# Miscellaneous
# =========================
fxconfig_msp_id: "{{ organization.name }}MSP"
