#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Postgres DB workload using generic k8s flow
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres
    tasks_from: k8s/rm
