#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure fetched log directory exists
  ansible.builtin.file:
    path: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}"
    state: directory
    mode: "0o755"

- name: Fetch Fabric-X Loadgen pod logs
  kubernetes.core.k8s_log:
    namespace: "{{ k8s_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ loadgen_k8s_resource_name }}"
    container: loadgen
  register: loadgen_k8s_logs
  failed_when: false

- name: Write Fabric-X Loadgen logs
  ansible.builtin.copy:
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/logs.txt"
    mode: "0o644"
    content: "{{ loadgen_k8s_logs.log | default('') }}"
