#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start cAdvisor container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.cadvisor
    tasks_from: container/start
  when: cadvisor_use_container
