#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Orderer Consenter
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_consenter/teardown

- name: Remove Fabric-X Orderer Consenter binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: bin/rm
  when: orderer_use_bin

- name: Remove Fabric-X Orderer Consenter crypto files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: crypto/rm

- name: Remove Fabric-X Orderer Consenter configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: config/rm
