#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ping Semaphore UI
  hosts: "{{ target_hosts | default('semaphore_ui') }}:&semaphore_ui"
  tasks:
    - name: Check that the Semaphore UI port is open
      ansible.builtin.include_role:
        name: hyperledger.fabricx.semaphore_ui
        tasks_from: ping
      when:
        - semaphore_ui_port is defined
