#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Semaphore UI
  hosts: "{{ target_hosts | default('semaphore_ui') }}:&semaphore_ui"
  tasks:
    - name: Start the Semaphore UI binary
      ansible.builtin.include_role:
        name: hyperledger.fabricx.semaphore_ui
        tasks_from: start
      when:
        - semaphore_ui_port is defined
