#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Collect the Fabric-X Orderer metrics
  hosts: "{{ target_hosts | default('fabric_x_orderers') }}:&fabric_x_orderers"
  tasks:
    - name: Collect Fabric-X Orderer components metrics
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: get_metrics
