#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create imagePullSecret "{{ k8s_image_pull_secret }}" in namespace "{{ k8s_namespace }}"
  kubernetes.core.k8s:
    state: present
    template:
      path: registry/image_pull_secret.yaml.j2
