#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =======================
# bin / container — Master
# =======================
- name: Check that the Yugabyte master node ports are open
  vars:
    utils_ports_to_ping:
      - "{{ yugabyte_master_webserver_port }}"
      - "{{ yugabyte_master_rpc_bind_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when:
    - not yugabyte_use_k8s
    - yugabyte_component_type == 'master'

# =======================
# bin / container — Tablet
# =======================
- name: Check that the Yugabyte tablet node ports are open
  vars:
    utils_ports_to_ping:
      - "{{ yugabyte_tablet_pgsql_bind_port }}"
      - "{{ yugabyte_tablet_rpc_bind_port }}"
      - "{{ yugabyte_tablet_webserver_port }}"
      - "{{ yugabyte_tablet_pgsql_web_port }}"
      - "{{ yugabyte_tablet_cql_bind_port }}"
      - "{{ yugabyte_tablet_cql_web_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when:
    - not yugabyte_use_k8s
    - yugabyte_component_type == 'tablet'

# =======================
# k8s
# =======================
- name: Check that the Yugabyte node ports are open (k8s)
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: k8s/ping
  when: yugabyte_use_k8s
