#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Loki container
  vars:
    container_name: "{{ loki_container_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: stop
  when: loki_use_container
