#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Yugabyte tablet StatefulSet
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ yugabyte_k8s_resource_name }}"
    namespace: "{{ k8s_namespace }}"

- name: Delete Yugabyte tablet headless Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ yugabyte_k8s_resource_name }}"
    namespace: "{{ k8s_namespace }}"

- name: Delete Yugabyte tablet NodePort Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ yugabyte_k8s_resource_name }}-nodeport"
    namespace: "{{ k8s_namespace }}"
  when:
    - yugabyte_k8s_tablet_pgsql_node_port is defined or
      yugabyte_k8s_tablet_rpc_node_port is defined or
      yugabyte_k8s_tablet_webserver_node_port is defined or
      yugabyte_k8s_tablet_pgsql_web_node_port is defined or
      yugabyte_k8s_tablet_cql_bind_node_port is defined or
      yugabyte_k8s_tablet_cql_web_node_port is defined

- name: Delete Yugabyte tablet LoadBalancer Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ yugabyte_k8s_resource_name }}-loadbalancer"
    namespace: "{{ k8s_namespace }}"
  when:
    - yugabyte_k8s_loadbalancer_expose_tablet_pgsql_port or
      yugabyte_k8s_loadbalancer_expose_tablet_rpc_port or
      yugabyte_k8s_loadbalancer_expose_tablet_webserver_port or
      yugabyte_k8s_loadbalancer_expose_tablet_pgsql_web_port or
      yugabyte_k8s_loadbalancer_expose_tablet_cql_bind_port or
      yugabyte_k8s_loadbalancer_expose_tablet_cql_web_port
