name: Bug report
description: Report a bug for `hyperledger.fabricx` Ansible collection
title: "[BUG] Title"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: List exact steps triggering the bug, including inventory and playbook snippets if possible.
      placeholder: Command `make start` fails with inventory `fabric-x.yaml` when running the playbook...
    validations:
      required: true
  - type: input
    id: ansible_version
    attributes:
      label: Ansible and collection versions
      description: |
        **Tip**: `ansible --version`

        **Tip** `ansible-galaxy collection list | grep "hyperledger.fabricx"`
      placeholder: |
        ansible [core 2.20.0], hyperledger.fabricx 0.5.11
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Target OS/platform
      placeholder: |
        ex: Ubuntu 22.04, RHEL 9, Darwin 14.x
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: |
        Paste logs or attach screenshots showing the error.

        **Tip**: You can attach files by dragging files in this area.
      render: shell
    validations:
      required: true
