#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Block Explorer UI container
  vars:
    container_name: "{{ block_explorer_ui_container_name }}"
    container_image: "{{ block_explorer_ui_image }}"
    container_env:
      PORT: "{{ block_explorer_ui_port | string }}"
      HOSTNAME: "0.0.0.0"
      BACKEND_URL: "http://{{ hostvars[block_explorer_host].ansible_host }}:{{ hostvars[block_explorer_host].block_explorer_port }}"
      NEXT_PUBLIC_BACKEND_DISPLAY_URL: "http://{{ hostvars[block_explorer_host].ansible_host }}:{{ hostvars[block_explorer_host].block_explorer_port }}"
    container_ports:
      - "{{ block_explorer_ui_port }}:{{ block_explorer_ui_port }}"
    container_healthcheck_test: >-
      wget --quiet --tries=1 --spider
      http://localhost:{{ block_explorer_ui_port }}/api/health
    container_wait_until_running: true
    container_run_as_host_user: true
    container_wait_port: "{{ block_explorer_ui_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
