#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure configtxlator artifacts directory exists
  ansible.builtin.file:
    path: "{{ configtxlator_artifacts_dir }}"
    state: directory
    mode: "0o755"

- name: Run {{ configtxlator_bin_name }} compute_update as container
  vars:
    container_name: "{{ configtxlator_container_name }}"
    container_image: "{{ configtxlator_image }}"
    container_command: >-
      {{ configtxlator_bin_name }} compute_update
      --channel_id {{ configtxlator_channel_id }}
      --original {{ configtxlator_container_artifacts_dir }}/{{ configtxlator_original_file | basename }}
      --updated {{ configtxlator_container_artifacts_dir }}/{{ configtxlator_updated_file | basename }}
      --output {{ configtxlator_container_artifacts_dir }}/{{ configtxlator_output_file | basename }}
    container_volumes:
      - "{{ configtxlator_artifacts_dir }}:{{ configtxlator_container_artifacts_dir }}:z"
    container_run_detach_mode: false
    container_run_as_host_user: true
    container_autoremove: true
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
