#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Initialize the committer database using generic k8s flow
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/init_db
