#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if Fabric-X Orderer Assembler MSP admin certs directory exists
  ansible.builtin.stat:
    path: "{{ orderer_remote_config_dir }}/msp/admincerts"
  register: orderer_admincerts_stat

- name: Apply Fabric-X Orderer Assembler Service
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/service.yaml.j2

- name: Apply Fabric-X Orderer Assembler NodePort Service
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/service-nodeport.yaml.j2

- name: Apply Fabric-X Orderer Assembler StatefulSet
  vars:
    orderer_k8s_command: assembler
    orderer_k8s_has_admincerts: "{{ orderer_admincerts_stat.stat.exists and orderer_admincerts_stat.stat.isdir }}"
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/statefulset.yaml.j2
    wait: "{{ orderer_k8s_wait }}"
    wait_timeout: "{{ orderer_k8s_wait_timeout }}"
