#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# mTLS client certs
# =========================
- name: Initialize mTLS client cert list
  ansible.builtin.set_fact:
    committer_k8s_mtls_client_certs: []
  when:
    - committer_use_mtls
    - committer_mtls_clients is defined

- name: Build mTLS client cert list
  vars:
    committer_k8s_mtls_client_cert:
      name: "{{ current_committer_mtls_client }}"
      path: "{{ committer_remote_config_dir }}/mtls/{{ current_committer_mtls_client }}/ca.crt"
  ansible.builtin.set_fact:
    committer_k8s_mtls_client_certs: "{{ committer_k8s_mtls_client_certs + [committer_k8s_mtls_client_cert] }}"
  loop: "{{ committer_mtls_clients }}"
  loop_control:
    loop_var: current_committer_mtls_client
    label: "{{ current_committer_mtls_client }}"
  when:
    - committer_use_mtls
    - committer_mtls_clients is defined

# =========================
# mTLS org certs
# =========================
- name: Initialize mTLS org cert list
  ansible.builtin.set_fact:
    committer_k8s_mtls_org_certs: []
  when:
    - committer_use_mtls
    - committer_mtls_orgs is defined

- name: Build mTLS org cert list
  vars:
    committer_k8s_mtls_org_cert:
      domain: "{{ current_committer_mtls_org.domain }}"
      path: "{{ committer_remote_config_dir }}/mtls/{{ current_committer_mtls_org.domain }}/ca.crt"
  ansible.builtin.set_fact:
    committer_k8s_mtls_org_certs: "{{ committer_k8s_mtls_org_certs + [committer_k8s_mtls_org_cert] }}"
  loop: "{{ committer_mtls_orgs }}"
  loop_control:
    loop_var: current_committer_mtls_org
    label: "{{ current_committer_mtls_org.domain }}"
  when:
    - committer_use_mtls
    - committer_mtls_orgs is defined
