#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure Committer Sidecar data directory exists
  ansible.builtin.file:
    path: "{{ committer_remote_data_dir }}"
    state: directory
    mode: "0o755"

- name: Start Hyperledger Fabric-X Committer Sidecar binary
  vars:
    bin_command: >-
      {{ committer_bin_name }} start-sidecar
      --config={{ committer_remote_config_dir }}/{{ committer_config_file }}
    bin_wait_until_running: true
    bin_wait_port: "{{ committer_rpc_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
