#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Semaphore UI configuration files
  ansible.builtin.file:
    path: "{{ semaphore_ui_remote_config_dir }}"
    state: absent
