#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete OpenShift Route "{{ openshift_route_name }}"
  kubernetes.core.k8s:
    state: absent
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ openshift_route_name }}"
    namespace: "{{ k8s_namespace }}"
