#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Apply Alloy RBAC (cluster-scoped)
  vars:
    k8s_rbac_resource_name: "{{ alloy_k8s_resource_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: rbac/apply
  when:
    - alloy_k8s_cluster_scope

- name: Apply Alloy RBAC (namespace-scoped)
  vars:
    k8s_rbac_resource_name: "{{ alloy_k8s_resource_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: rbac/apply-namespaced
  when:
    - not alloy_k8s_cluster_scope

- name: Apply Alloy ConfigMap
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k8s_namespace | default('default') }}"
    template:
      path: k8s/configmap.yaml.j2
