#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Set Prometheus scrape services for Fabric-X Orderer
  vars:
    orderer_hosts_with_vars: >-
      {{
        orderer_hosts
        | map('extract', hostvars)
        | selectattr('orderer_component_type', 'defined')
      }}
    orderer_assembler_hosts: >-
      {{
        orderer_hosts_with_vars
        | selectattr('orderer_component_type', '==', 'assembler')
        | map(attribute='inventory_hostname')
        | list
      }}
    orderer_consenter_hosts: >-
      {{
        orderer_hosts_with_vars
        | selectattr('orderer_component_type', '==', 'consensus')
        | map(attribute='inventory_hostname')
        | list
      }}
    orderer_router_hosts: >-
      {{
        orderer_hosts_with_vars
        | selectattr('orderer_component_type', '==', 'router')
        | map(attribute='inventory_hostname')
        | list
      }}
    orderer_batcher_hosts: >-
      {{
        orderer_hosts_with_vars
        | selectattr('orderer_component_type', '==', 'batcher')
        | map(attribute='inventory_hostname')
        | list
      }}
    orderer_assembler_ref_host: "{{ orderer_assembler_hosts | first }}"
    orderer_consenter_ref_host: "{{ orderer_consenter_hosts | first }}"
    orderer_router_ref_host: "{{ orderer_router_hosts | first }}"
    orderer_batcher_ref_host: "{{ orderer_batcher_hosts | first }}"
    orderer_scrape_services:
      - job_name: "assembler_service.{{ hostvars[orderer_assembler_ref_host].organization.domain }}"
        use_tls: "{{ hostvars[orderer_assembler_ref_host].orderer_operations_use_tls | default(false) }}"
        use_mtls: "{{ hostvars[orderer_assembler_ref_host].orderer_operations_use_mtls | default(false) }}"
        tls_ca_file: "{{ fetched_artifacts_dir }}/{{ orderer_assembler_ref_host }}/tls/ca.crt"
        targets:
          - hosts: "{{ orderer_assembler_hosts }}"
            port_to_scrape: orderer_operations_port
      - job_name: "consenter_service.{{ hostvars[orderer_consenter_ref_host].organization.domain }}"
        use_tls: "{{ hostvars[orderer_consenter_ref_host].orderer_operations_use_tls | default(false) }}"
        use_mtls: "{{ hostvars[orderer_consenter_ref_host].orderer_operations_use_mtls | default(false) }}"
        tls_ca_file: "{{ fetched_artifacts_dir }}/{{ orderer_consenter_ref_host }}/tls/ca.crt"
        targets:
          - hosts: "{{ orderer_consenter_hosts }}"
            port_to_scrape: orderer_operations_port
      - job_name: "router_service.{{ hostvars[orderer_router_ref_host].organization.domain }}"
        use_tls: "{{ hostvars[orderer_router_ref_host].orderer_operations_use_tls | default(false) }}"
        use_mtls: "{{ hostvars[orderer_router_ref_host].orderer_operations_use_mtls | default(false) }}"
        tls_ca_file: "{{ fetched_artifacts_dir }}/{{ orderer_router_ref_host }}/tls/ca.crt"
        targets:
          - hosts: "{{ orderer_router_hosts }}"
            port_to_scrape: orderer_operations_port
      - job_name: "batcher_service.{{ hostvars[orderer_batcher_ref_host].organization.domain }}"
        use_tls: "{{ hostvars[orderer_batcher_ref_host].orderer_operations_use_tls | default(false) }}"
        use_mtls: "{{ hostvars[orderer_batcher_ref_host].orderer_operations_use_mtls | default(false) }}"
        tls_ca_file: "{{ fetched_artifacts_dir }}/{{ orderer_batcher_ref_host }}/tls/ca.crt"
        targets:
          - hosts: "{{ orderer_batcher_hosts }}"
            port_to_scrape: orderer_operations_port
  ansible.builtin.set_fact:
    orderer_prometheus_scrape_services: "{{ (orderer_prometheus_scrape_services | default([])) + orderer_scrape_services }}"
