#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Transfer Fabric-X Loadgen config files
  hosts: "{{ target_hosts | default('load_generators') }}:&load_generators"
  tasks:
    - name: Transfer Fabric-X Loadgen config files
      vars:
        reference_committer_hosts: >-
          {{
            (
              groups['fabric_x_committers']
              | default([])
              | map('extract', hostvars)
              | selectattr('organization', 'defined')
              | selectattr('organization.domain', 'defined')
              | selectattr('organization.domain', '==', organization.domain | default(''))
              | map(attribute='inventory_hostname')
              | list
            )
            or groups['fabric_x_committers'] | default([])
          }}
        orderer_hosts: "{{ groups['fabric_x_orderers'] | default([]) }}"
      block:
        - name: Transfer Fabric-X Loadgen config files
          vars:
            committer_hosts: "{{ reference_committer_hosts }}"
          ansible.builtin.include_role:
            name: hyperledger.fabricx.loadgen
            tasks_from: config/transfer
