#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Node Exporter TLS directory
  ansible.builtin.file:
    path: "{{ node_exporter_remote_config_dir }}/tls"
    state: absent
  when:
    - node_exporter_use_tls

- name: Delete Node Exporter Kubernetes Secret
  kubernetes.core.k8s:
    state: absent
    kind: Secret
    name: "{{ node_exporter_k8s_resource_name }}"
    namespace: "{{ k8s_namespace }}"
  when: node_exporter_use_k8s
