#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Node Exporter TLS directory
  ansible.builtin.file:
    path: "{{ node_exporter_remote_config_dir }}/tls"
    state: absent
  when:
    - node_exporter_use_tls

- name: Delete Node Exporter Kubernetes Secret
  ansible.builtin.include_role:
    name: hyperledger.fabricx.node_exporter
    tasks_from: k8s/crypto/rm
  when: node_exporter_use_k8s or node_exporter_use_openshift
