#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Committer validator
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: validator/teardown

- name: Remove Fabric-X Committer validator binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: bin/rm
  when:
    - committer_use_bin

- name: Remove Fabric-X Committer validator configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: config/rm

- name: Remove Fabric-X Committer validator crypto material
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: crypto/rm
