#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Committer sidecar Kubernetes workload
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: sidecar/k8s/teardown

- name: Remove Fabric-X Committer sidecar ConfigMap
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/config/rm

- name: Remove Fabric-X Committer sidecar Secret
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/crypto/rm
