#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check that the MSP path is defined
  ansible.builtin.fail:
    msg: "No path to the meta namespace admin MSP is indicated. Set it via 'fxconfig_msp_config_path'."
  when:
    - fxconfig_msp_config_path is not defined

# =========================
# Configuration
# =========================
- name: Ensure the config directory for fxconfig exists
  ansible.builtin.file:
    path: "{{ fxconfig_remote_config_dir }}"
    state: directory
    mode: "0o755"

- name: Setup the fxconfig configuration file
  vars:
    fxconfig_config_dir: >-
      {{
        fxconfig_remote_config_dir
        if fxconfig_use_bin
        else fxconfig_container_config_dir
      }}
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "{{ fxconfig_remote_config_dir }}/{{ fxconfig_config_file }}"
    mode: "0o644"

# =========================
# MSP material
# =========================
- name: Transfer the MSP material
  ansible.builtin.copy:
    src: "{{ fxconfig_msp_config_path }}"
    dest: "{{ fxconfig_remote_config_dir }}"
    remote_src: true
    mode: "preserve"

# =========================
# TLS material
# =========================
- name: Setup TLS material for fxconfig
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxconfig
    tasks_from: config/tls/transfer
  when:
    - (hostvars[committer_query_service_host].committer_use_tls is defined and hostvars[committer_query_service_host].committer_use_tls)
      or
      (hostvars[orderer_router_host].orderer_use_tls is defined and hostvars[orderer_router_host].orderer_use_tls)

# =========================
# mTLS material
# =========================
- name: Setup mTLS material for fxconfig
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxconfig
    tasks_from: config/mtls/transfer
  when:
    - (hostvars[committer_query_service_host].committer_use_mtls is defined and hostvars[committer_query_service_host].committer_use_mtls)
      or
      (hostvars[orderer_router_host].orderer_use_mtls is defined and hostvars[orderer_router_host].orderer_use_mtls)
