#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Compute Git directory name from Git Repo name
  ansible.builtin.include_role:
    name: hyperledger.fabricx.git
    tasks_from: get_repo_name

- name: Ensure directory where to clone exists
  ansible.builtin.file:
    path: "{{ git_dir }}/{{ git_repo_name }}"
    state: directory
    mode: "0o755"

- name: Clone Git Repo {{ git_uri }}@{{ git_commit }}
  ansible.builtin.git:
    repo: "{{ git_uri }}"
    dest: "{{ git_dir }}/{{ git_repo_name }}"
    version: "{{ git_commit }}"
    force: true
