#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Compute Git Repository name from Git Repository
  ansible.builtin.set_fact:
    git_repo_name: "{{ (git_repo | basename) }}@{{ git_commit }}"
