#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create the cryptogen output folder
  ansible.builtin.file:
    state: directory
    path: "{{ cryptogen_output_dir }}"
    mode: "0o755"

- name: Start the cryptogen binary
  vars:
    bin_run_with_tmux: false
    bin_remote_dir: "{{ cli_bin_dir }}"
    bin_command: >-
      {{ cryptogen_bin_name }} extend
      --config={{ cryptogen_artifacts_dir }}/{{ cryptogen_config_file }}
      --input={{ cryptogen_output_dir }}
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
