#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check that the binary name has been defined
  ansible.builtin.fail:
    msg: "No bin name is indicated. Set it via 'bin_name'."
  when: bin_name is not defined

- name: Clone go binary code as git repository
  vars:
    git_dir: "{{ bin_source_code_dir if bin_build_on_control_node else bin_remote_source_code_dir }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.git
    tasks_from: clone

- name: Build go code as binary
  vars:
    go_source_code_path: "{{ bin_source_code_dir if bin_build_on_control_node else bin_remote_source_code_dir }}/{{ git_repo_name }}"
    go_output_name: "{{ bin_output_dir if bin_build_on_control_node else bin_remote_dir }}/{{ bin_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.go
    tasks_from: build
