#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Install go package as binary
  vars:
    go_output_dir: "{{ bin_output_dir if bin_build_on_control_node else bin_remote_dir }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.go
    tasks_from: install
