#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Block Explorer UI
  ansible.builtin.include_role:
    name: hyperledger.fabricx.block_explorer_ui
    tasks_from: teardown
