#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Postgres Exporter config files
  ansible.builtin.file:
    path: "{{ postgres_exporter_remote_config_dir }}"
    state: absent

- name: Delete Postgres Exporter Kubernetes ConfigMap
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres_exporter
    tasks_from: k8s/config/rm
  when: postgres_exporter_use_k8s
