#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =======================
# bin / container
# =======================
- name: Check that the Jaeger ports are open
  vars:
    utils_ports_to_ping:
      - "{{ jaeger_ui_port }}"
      - "{{ jaeger_admin_port }}"
      - "{{ jaeger_http_server_port }}"
      - "{{ jaeger_http_collector_port }}"
      - "{{ jaeger_grpc_server_port }}"
      - "{{ jaeger_collector_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when: not (jaeger_use_k8s or jaeger_use_openshift)

# =======================
# k8s
# =======================
- name: Check that the node ports are open
  ansible.builtin.include_role:
    name: hyperledger.fabricx.jaeger
    tasks_from: k8s/ping
  when: jaeger_use_k8s

# =======================
# openshift
# =======================
- name: Check that the OpenShift routes and Kubernetes services are open
  ansible.builtin.include_role:
    name: hyperledger.fabricx.jaeger
    tasks_from: openshift/ping
  when: jaeger_use_openshift
