#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Jaeger container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.jaeger
    tasks_from: container/start
  when: jaeger_use_container

- name: Start Jaeger on Kubernetes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.jaeger
    tasks_from: k8s/start
  when: jaeger_use_k8s
