#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Fabric-X Orderer nodes
  when: orderer_deployment_mode in ['bin', 'container']
  block:
    - name: Stop Fabric-X Orderer router nodes
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: "{{ orderer_deployment_mode }}/stop"
      when: orderer_component_type == 'router'

    - name: Stop Fabric-X Orderer assembler nodes
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: "{{ orderer_deployment_mode }}/stop"
      when: orderer_component_type == 'assembler'

    - name: Stop Fabric-X Orderer batcher nodes
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: "{{ orderer_deployment_mode }}/stop"
      when: orderer_component_type == 'batcher'

    - name: Stop Fabric-X Orderer consensus nodes
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: "{{ orderer_deployment_mode }}/stop"
      when: orderer_component_type == 'consensus'
