#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Fabric-X Orderer nodes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: "{{ orderer_deployment_mode }}/stop"
  when:
    - orderer_deployment_mode in ['bin', 'container']
    - orderer_component_type is defined
