#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check that the go build output has been defined
  ansible.builtin.fail:
    msg: "No go build output has been defined, but required to build the binary. Set it via 'go_output_name'."
  when: go_output_name is not defined

- name: Check that the go source path has been defined
  ansible.builtin.fail:
    msg: "No path for the source code of the binary has been defined. Set it via 'go_source_code_path'."
  when: go_source_code_path is not defined

- name: Map host platform to GOOS and GOARCH
  ansible.builtin.include_role:
    name: hyperledger.fabricx.go
    tasks_from: map_platform
  when:
    - go_host_to_map is defined

- name: Set CC for cross-compilation on macOS with CGO_ENABLED
  ansible.builtin.set_fact:
    go_cc_compiler: x86_64-unknown-linux-gnu-gcc
  when:
    - ansible_facts.system == 'Darwin'
    - go_cgo_enabled
    - go_os == 'linux'
    - go_arch == 'amd64'

- name: Build the binary {{ go_output_name }}
  ansible.builtin.command: >-
    go build
    -C {{ go_source_code_path }}/{{ go_source_code_package }}
    -o {{ go_output_name }}
    {% if go_tags is defined %}
    -tags="{{ go_tags | join(',') }}"
    {% endif %}
  environment:
    GOOS: "{{ go_os }}"
    GOARCH: "{{ go_arch }}"
    CGO_ENABLED: "{{ 1 if go_cgo_enabled else 0 }}"
    CC: "{{ go_cc_compiler | default('') if go_cgo_enabled else '' }}"
  register: go_build_result
  changed_when: go_build_result.rc != 0
