#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get Podman information
  containers.podman.podman_system_info:
  register: container_podman_info_output

- name: Set Podman socket from remote information
  when:
    - container_podman_info_output.podman_system_info.host.remoteSocket.exists | default(false)
  vars:
    container_podman_remote_socket: "{{ container_podman_info_output.podman_system_info.host.remoteSocket.path }}"
    container_podman_remote_socket_is_unix: "{{ container_podman_remote_socket | regex_search('^unix://') is not none }}"
  block:
    - name: Set Unix Podman socket and path
      ansible.builtin.set_fact:
        container_socket: "{{ container_podman_remote_socket }}"
        container_socket_path: "{{ container_podman_remote_socket | regex_replace('^unix://', '') }}"
      when:
        - container_podman_remote_socket_is_unix
    - name: Prepend Unix scheme to bare Podman socket
      ansible.builtin.set_fact:
        container_socket: "unix://{{ container_podman_remote_socket }}"
        container_socket_path: "{{ container_podman_remote_socket }}"
      when:
        - not container_podman_remote_socket_is_unix
