#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create Fabric-X namespaces
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Create FabricX namespaces with fxconfig
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: namespaces_create
      loop: "{{ organization.users }}"
      loop_control:
        loop_var: current_user
        label: "{{ organization.domain }}:{{ current_user.name }}"
      when:
        - organization is defined
        - organization.users is defined
