#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create Fabric-X namespaces transactions on the control node
  hosts: localhost
  tasks:
    - name: Group organization roles per namespace
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: namespace_group
    - name: Create FabricX namespaces with fxconfig on the control node
      vars:
        bin_remote_dir: "{{ cli_bin_dir }}"
        fxconfig_namespace: "{{ current_namespace_with_orgs.namespace }}"
        fxconfig_namespace_policy: "AND({{ current_namespace_with_orgs.org_roles | map('regex_replace', '^(.*)$', \"'\\1'\") | join(', ') }})"
        fxconfig_output: "{{ config_build_dir }}/fxconfig-artifacts/{{ fxconfig_namespace }}/to_endorse/ns.json"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: namespace_create
      loop: "{{ fxconfig_orgs_per_namespaces.values() }}"
      loop_control:
        loop_var: current_namespace_with_orgs
        label: "{{ fxconfig_namespace }}"
      when:
        - fxconfig_orgs_per_namespaces is defined

- name: Endorse Fabric-X namespace transactions
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Endorse FabricX namespaces with fxconfig
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: endorse
      loop: "{{ organization.namespaces }}"
      loop_control:
        loop_var: fxconfig_namespace
        label: "{{ fxconfig_namespace }}"
      when:
        - organization is defined
        - organization.namespaces is defined

- name: Merge endorsed Fabric-X namespaces transactions on the control node
  hosts: localhost
  tasks:
    - name: Merge endorsed FabricX namespaces transactions in one single multi-endorsed transaction
      vars:
        bin_remote_dir: "{{ cli_bin_dir }}"
        fxconfig_endorsed_txs_dir: "{{ config_build_dir }}/fxconfig-artifacts/{{ fxconfig_namespace }}/endorsed"
        fxconfig_output: "{{ config_build_dir }}/fxconfig-artifacts/{{ fxconfig_namespace }}/ns.json"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: merge
      loop: >-
        {{
          groups['all']
          | map('extract', hostvars)
          | map('to_json')
          | map('from_json')
          | selectattr('organization', 'defined')
          | map(attribute='organization')
          | selectattr('namespaces', 'defined')
          | map(attribute='namespaces')
          | flatten
        }}
      loop_control:
        loop_var: fxconfig_namespace
        label: "{{ fxconfig_namespace }}"

# TODO: submission should be run by one single node per namespace
- name: Submit Fabric-X namespace transactions
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Endorse FabricX namespaces with fxconfig
      vars:
        fxconfig_tx_to_submit_path: "{{ config_build_dir }}/fxconfig-artifacts/{{ fxconfig_namespace }}/ns.json"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: submit
      loop: "{{ organization.namespaces }}"
      loop_control:
        loop_var: fxconfig_namespace
        label: "{{ fxconfig_namespace }}"
      when:
        - organization is defined
        - organization.namespaces is defined
