#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Wipe fxconfig
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Wipe fxconfig
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fxconfig
        tasks_from: wipe
      when:
        - organization is defined
        - organization.users is defined
