#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Fabric-X Orderer StatefulSet
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ orderer_k8s_resource_name }}"
    namespace: "{{ k8s_namespace }}"

- name: Delete Fabric-X Orderer Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ orderer_k8s_resource_name }}"
    namespace: "{{ k8s_namespace }}"

- name: Delete Fabric-X Orderer NodePort Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ orderer_k8s_resource_name }}-nodeport"
    namespace: "{{ k8s_namespace }}"
  when:
    - orderer_k8s_rpc_node_port is defined or
      orderer_k8s_metrics_node_port is defined

- name: Delete Fabric-X Orderer LoadBalancer Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ orderer_k8s_resource_name }}-loadbalancer"
    namespace: "{{ k8s_namespace }}"
  when:
    - orderer_k8s_loadbalancer_expose_rpc_port or
      orderer_k8s_loadbalancer_expose_metrics_port
