#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clean the /ca folder in the output dir
  ansible.builtin.file:
    path: "{{ idemixgen_output_dir }}/ca"
    state: absent

- name: Clean the /msp folder in the output dir
  ansible.builtin.file:
    path: "{{ idemixgen_output_dir }}/msp"
    state: absent

- name: Generate the idemix CA key material
  vars:
    bin_run_with_tmux: false
    bin_remote_dir: "{{ cli_bin_dir }}"
    bin_command: >-
      {{ idemixgen_bin_name }} ca-keygen
      --curve {{ idemixgen_curve_id }}
      --output {{ idemixgen_output_dir }}
      {% if idemixgen_use_aries %}
      --aries
      {% endif %}
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
