#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: List Hyperledger Fabric-X Committer namespaces
  vars:
    bin_env:
      FXCONFIG_LOGGING_LEVEL: "{{ fxconfig_log_level }}"
      FXCONFIG_LOGGING_FORMAT: "{{ fxconfig_log_format | quote }}"
    bin_command: >-
      {{ fxconfig_bin_name }} namespace
      list
      --config={{ fxconfig_remote_config_dir }}/{{ fxconfig_config_file }}
    bin_run_with_tmux: false
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start

- name: Print retrieved Fabric-X namespaces
  ansible.builtin.debug:
    msg: "{{ bin_output.stdout_lines }}"
  when:
    - bin_output is defined
