#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Yugabyte master Kubernetes resources
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: k8s/master/start
  when: yugabyte_component_type == 'master'

- name: Start Yugabyte tablet server Kubernetes resources
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: k8s/tablet/start
  when: yugabyte_component_type == 'tablet'
