#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if BCCSP is already enrolled
  vars:
    fabric_ca_bccsp_enrollment_cert_file: "{{ fabric_ca_cryptogenize_tls_cert_file if (fabric_ca_enrollment_profile is defined and fabric_ca_enrollment_profile == 'tls') else fabric_ca_cryptogenize_msp_signcert_file }}"
  ansible.builtin.stat:
    path: "{{ fabric_ca_msp_dir }}/{{ fabric_ca_bccsp_enrollment_cert_file }}"
  register: fabric_ca_msp_cert
  when:
    - fabric_ca_enrollment_type == 'bccsp'

- name: Check if Idemix already enrolled
  ansible.builtin.stat:
    path: "{{ fabric_ca_msp_dir }}/msp/user/SignerConfig"
  register: fabric_ca_idemix_signer
  when:
    - fabric_ca_enrollment_type == 'idemix'

- name: Prepare and enroll identity with Fabric CA client binary
  when:
    - (
      fabric_ca_enrollment_type == 'idemix'
      and not fabric_ca_idemix_signer.stat.exists
      )
      or (
      fabric_ca_enrollment_type == 'bccsp'
      and not fabric_ca_msp_cert.stat.exists
      )
  block:
    - name: Resolve effective Fabric CA connection port
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fabric_ca
        tasks_from: server/effective_address
    - name: Enroll identity with Fabric CA client binary
      vars:
        bin_env:
          FABRIC_CA_CLIENT_HOME: "{{ fabric_ca_msp_dir }}"
        bin_command: >-
          {{ fabric_ca_client_bin_name }}
          enroll
          -u {{ fabric_ca_scheme }}://{{ fabric_ca_identity.name }}:{{ fabric_ca_identity.secret }}@{{ fabric_ca_server_effective_address }}
          --caname {{ fabric_ca_name }}
          --mspdir {{ fabric_ca_msp_dir }}
          {% if fabric_ca_enrollment_type == 'idemix' %}
          --enrollment.type idemix
          --enrollment.profile idemix
          {% elif fabric_ca_enrollment_type == 'bccsp' %}
          {% if fabric_ca_enrollment_profile is defined and fabric_ca_enrollment_profile == 'tls' %}
          --myskfile {{ fabric_ca_cryptogenize_tls_key_file }}
          --mycertfile {{ fabric_ca_cryptogenize_tls_cert_file }}
          --mycacertfile {{ fabric_ca_cryptogenize_tls_ca_cert_file }}
          --enrollment.profile tls
          {% else %}
          --myskfile {{ fabric_ca_cryptogenize_msp_private_key_file }}
          --mycertfile {{ fabric_ca_cryptogenize_msp_signcert_file }}
          --mycacertfile {{ fabric_ca_cryptogenize_msp_ca_cert_file }}
          {% endif %}
          {% endif %}
          {% if fabric_ca_enrollment_type == 'bccsp' and fabric_ca_csr_hosts is defined and (fabric_ca_csr_hosts | length) > 0 %}
          {% for csr_host in fabric_ca_csr_hosts %}
          --csr.hosts {{ csr_host }}
          {% endfor %}
          {% endif %}
          {% if fabric_ca_use_tls and (fabric_ca_tls_certfile is defined) %}
          --tls.certfiles {{ fabric_ca_tls_certfile }}
          {% endif %}
        bin_run_with_tmux: false
        bin_collect_logs: false
      ansible.builtin.include_role:
        name: hyperledger.fabricx.bin
        tasks_from: start

- name: Copy NodeOUs configuration file
  ansible.builtin.template:
    src: nodeous-config.yaml.j2
    dest: "{{ fabric_ca_msp_dir }}/config.yaml"
    mode: "0o644"
  when:
    - fabric_ca_enrollment_type == 'bccsp'

- name: Adjust crypto to be as idemixgen produced crypto
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fabric_ca
    tasks_from: client/idemixgenize
  when:
    - fabric_ca_enrollment_type == 'idemix'
