#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Apply Fabric-X Orderer Consenter Service
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/service.yaml.j2

- name: Apply Fabric-X Orderer Consenter NodePort Service
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/service-nodeport.yaml.j2

- name: Apply Fabric-X Orderer Consenter StatefulSet
  vars:
    orderer_k8s_command: consensus
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/statefulset.yaml.j2
    wait: "{{ orderer_k8s_wait }}"
    wait_timeout: "{{ orderer_k8s_wait_timeout }}"
