#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Alloy StatefulSet
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ alloy_k8s_resource_name }}"
    namespace: "{{ k8s_namespace | default('default') }}"

- name: Delete Alloy Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ alloy_k8s_resource_name }}"
    namespace: "{{ k8s_namespace | default('default') }}"

- name: Delete Alloy NodePort Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ alloy_k8s_resource_name }}-nodeport"
    namespace: "{{ k8s_namespace | default('default') }}"
  when: alloy_k8s_node_port is defined

- name: Delete Alloy LoadBalancer Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ alloy_k8s_resource_name }}-loadbalancer"
    namespace: "{{ k8s_namespace | default('default') }}"
  when: alloy_k8s_loadbalancer_expose_port

- name: Delete Alloy configuration (ConfigMap)
  ansible.builtin.include_role:
    name: hyperledger.fabricx.alloy
    tasks_from: k8s/config/rm

- name: Delete Alloy RBAC resources
  kubernetes.core.k8s:
    state: absent
    api_version: "{{ current_alloy_rbac.api_version }}"
    kind: "{{ current_alloy_rbac.kind }}"
    name: "{{ alloy_k8s_resource_name }}"
    namespace: "{{ current_alloy_rbac.namespace | default(omit) }}"
  loop:
    - api_version: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      cluster_scope: true
    - api_version: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      cluster_scope: true
    - api_version: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      namespace: "{{ k8s_namespace | default('default') }}"
      cluster_scope: false
    - api_version: rbac.authorization.k8s.io/v1
      kind: Role
      namespace: "{{ k8s_namespace | default('default') }}"
      cluster_scope: false
    - api_version: v1
      kind: ServiceAccount
      namespace: "{{ k8s_namespace | default('default') }}"
      cluster_scope: false
  loop_control:
    loop_var: current_alloy_rbac
  when:
    - alloy_k8s_cluster_scope or not current_alloy_rbac.cluster_scope
