#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Fabric-X Committer query-service Kubernetes workload
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: query_service/k8s/rm
