#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =======================
# bin / container
# =======================
- name: Check that the Prometheus port is open
  vars:
    utils_ports_to_ping:
      - "{{ prometheus_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when: not prometheus_use_k8s

# =======================
# k8s
# =======================
- name: Check that the node ports are open (k8s)
  ansible.builtin.include_role:
    name: hyperledger.fabricx.prometheus
    tasks_from: k8s/ping
  when: prometheus_use_k8s
