#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Namespace
# =========================
- name: Ensure Kubernetes namespace exists
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ k8s_namespace }}"

# =========================
# Genesis block
# =========================
- name: Slurp Fabric-X Orderer genesis block
  ansible.builtin.slurp:
    src: "{{ orderer_remote_config_dir }}/genesis.block"
  register: orderer_slurp_genesis

# =========================
# mTLS client certs (conditional)
# =========================
- name: Initialize mTLS client cert list
  ansible.builtin.set_fact:
    orderer_k8s_mtls_client_certs: []
  when:
    - orderer_use_mtls
    - orderer_mtls_clients is defined

- name: Build mTLS client cert list
  vars:
    orderer_k8s_mtls_client_cert:
      name: "{{ current_orderer_mtls_client }}"
      path: "{{ orderer_remote_config_dir }}/mtls/{{ current_orderer_mtls_client }}/ca.crt"
  ansible.builtin.set_fact:
    orderer_k8s_mtls_client_certs: "{{ orderer_k8s_mtls_client_certs + [orderer_k8s_mtls_client_cert] }}"
  loop: "{{ orderer_mtls_clients }}"
  loop_control:
    loop_var: current_orderer_mtls_client
    label: "{{ current_orderer_mtls_client }}"
  when:
    - orderer_use_mtls
    - orderer_mtls_clients is defined

# =========================
# mTLS org certs (conditional)
# =========================
- name: Initialize mTLS org cert list
  ansible.builtin.set_fact:
    orderer_k8s_mtls_org_certs: []
  when:
    - orderer_use_mtls
    - orderer_mtls_orgs is defined

- name: Build mTLS org cert list
  vars:
    orderer_k8s_mtls_org_cert:
      domain: "{{ current_orderer_mtls_org.domain }}"
      path: "{{ orderer_remote_config_dir }}/mtls/{{ current_orderer_mtls_org.domain }}/ca.crt"
  ansible.builtin.set_fact:
    orderer_k8s_mtls_org_certs: "{{ orderer_k8s_mtls_org_certs + [orderer_k8s_mtls_org_cert] }}"
  loop: "{{ orderer_mtls_orgs }}"
  loop_control:
    loop_var: current_orderer_mtls_org
    label: "{{ current_orderer_mtls_org.domain }}"
  when:
    - orderer_use_mtls
    - orderer_mtls_orgs is defined

# =========================
# Apply ConfigMap
# =========================
- name: Apply Fabric-X Orderer ConfigMap
  vars:
    orderer_k8s_node_config_content: "{{ lookup('template', 'config-' + orderer_component_type + '.yaml.j2') }}"
    orderer_k8s_genesis_block_b64: "{{ orderer_slurp_genesis.content }}"
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/configmap.yaml.j2
