#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Yugabyte TLS directory
  ansible.builtin.file:
    path: "{{ yugabyte_remote_config_dir }}/tls"
    state: absent
  when:
    - yugabyte_use_tls

- name: Delete Yugabyte k8s Secret
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: "{{ yugabyte_k8s_resource_name }}-secret"
    namespace: "{{ k8s_namespace }}"
  when: yugabyte_use_k8s
