#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove ElasticSearch container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.elasticsearch
    tasks_from: container/rm
  when: elasticsearch_use_container

- name: Remove ElasticSearch Kubernetes workload
  ansible.builtin.include_role:
    name: hyperledger.fabricx.elasticsearch
    tasks_from: k8s/rm
  when: elasticsearch_use_k8s

- name: Teardown Elasticsearch on OpenShift
  ansible.builtin.include_role:
    name: hyperledger.fabricx.elasticsearch
    tasks_from: openshift/rm
  when: elasticsearch_use_openshift

- name: Remove ElasticSearch data
  ansible.builtin.include_role:
    name: hyperledger.fabricx.elasticsearch
    tasks_from: data/rm
