#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Fabric CAs crypto material
  hosts: "{{ target_hosts | default('fabric_cas') }}:&fabric_cas"
  tasks:
    - name: Fetch the Fabric CA DB certificates
      ansible.builtin.include_role:
        name: hyperledger.fabricx.postgres
        tasks_from: crypto/fetch
      when:
        - postgres_port is defined
    - name: Fetch the Fabric CA certificates
      vars:
        fabric_ca_orderer_organization: >-
          {{
            groups['all']
            | map('extract', hostvars)
            | selectattr('organization', 'defined')
            | selectattr('organization.domain', '==', organization.domain)
            | selectattr('organization.role', 'defined')
            | selectattr('organization.role', '==', 'orderer')
            | length > 0
          }}
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fabric_ca
        tasks_from: server/crypto/fetch
      when:
        - fabric_ca_port is defined
