#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Gather and register identities on each CA host
  hosts: "{{ target_hosts | default('fabric_ca_servers') }}:&fabric_ca_servers"
  tasks:
    - name: List registered identities on Fabric CA
      vars:
        fabric_ca_tls_certfile: "{{ fabric_ca_server_remote_config_dir }}/{{ fabric_ca_server_tls_cert_file }}"
        fabric_ca_host: "{{ inventory_hostname }}"
        fabric_ca_msp_dir: "{{ fabric_ca_server_remote_config_dir }}/{{ fabric_ca_admin.name }}/msp"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fabric_ca
        tasks_from: client/identity_list
      when:
        - fabric_ca_admin is defined
    - name: Gather Fabric CA identities
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fabric_ca
        tasks_from: client/gather_identities
    - name: Register missing identities on Fabric CA
      vars:
        fabric_ca_tls_certfile: "{{ fabric_ca_server_remote_config_dir }}/{{ fabric_ca_server_tls_cert_file }}"
        fabric_ca_host: "{{ inventory_hostname }}"
        fabric_ca_msp_dir: "{{ fabric_ca_server_remote_config_dir }}/{{ fabric_ca_admin.name }}/msp"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fabric_ca
        tasks_from: client/register
      loop: "{{ fabric_ca_gathered_identities }}"
      loop_control:
        loop_var: fabric_ca_identity
        label: "{{ fabric_ca_identity.name }}"
      when:
        - fabric_ca_admin is defined
        - fabric_ca_identity.name not in (fabric_ca_registered_identities_names | default([]))
