#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# MSP certs
# =========================
- name: Copy Hyperledger Fabric-X Committer sign certificate into organization knowncerts
  ansible.builtin.copy:
    src: "{{ cryptogen_artifacts_dir }}/crypto/peerOrganizations/{{ organization.domain }}/peers/{{ committer_crypto_name }}.{{ organization.domain }}/msp/signcerts/{{ committer_crypto_name }}.{{ organization.domain }}-cert.pem"
    dest: "{{ fetched_artifacts_dir }}/crypto/peerOrganizations/{{ organization.domain }}/msp/knowncerts/{{ committer_crypto_name }}.{{ organization.domain }}-cert.pem"
    mode: preserve
  delegate_to: localhost
  when:
    - organization.fabric_ca_host is undefined

- name: Fetch Hyperledger Fabric-X Committer sidecar sign certificate into organization knowncerts
  ansible.builtin.fetch:
    src: "{{ committer_remote_config_dir }}/msp/signcerts/{{ committer_crypto_name }}.{{ organization.domain }}-cert.pem"
    dest: "{{ fetched_artifacts_dir }}/crypto/peerOrganizations/{{ organization.domain }}/msp/knowncerts/{{ committer_crypto_name }}.{{ organization.domain }}-cert.pem"
    flat: true
  when:
    - organization.fabric_ca_host is defined
    - committer_component_type == 'sidecar'

# =========================
# TLS certs
# =========================
- name: Fetch Hyperledger Fabric-X Committer TLS certificates
  when:
    - committer_use_tls
  block:
    - name: Fetch Hyperledger Fabric-X Committer TLS CA certificate
      ansible.builtin.fetch:
        src: "{{ committer_remote_config_dir }}/tls/ca.crt"
        dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/ca.crt"
        flat: true
    - name: Fetch Hyperledger Fabric-X Committer TLS certificate
      ansible.builtin.fetch:
        src: "{{ committer_remote_config_dir }}/tls/server.crt"
        dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/server.crt"
        flat: true
