#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Loki StatefulSet
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ loki_k8s_resource_name }}"
    namespace: "{{ k8s_namespace | default('default') }}"

- name: Remove Loki Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ loki_k8s_resource_name }}"
    namespace: "{{ k8s_namespace | default('default') }}"

- name: Remove Loki NodePort Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ loki_k8s_resource_name }}-nodeport"
    namespace: "{{ k8s_namespace | default('default') }}"
  when: loki_k8s_node_port is defined

- name: Remove Loki LoadBalancer Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ loki_k8s_resource_name }}-loadbalancer"
    namespace: "{{ k8s_namespace | default('default') }}"
  when: loki_k8s_loadbalancer_expose_port
