#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure Kubernetes namespace exists for Loki
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: namespace/create

- name: Apply Loki Service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k8s_namespace | default('default') }}"
    template:
      path: k8s/service.yaml.j2

- name: Apply Loki NodePort Service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k8s_namespace | default('default') }}"
    template:
      path: k8s/service-nodeport.yaml.j2
  when: loki_k8s_node_port is defined

- name: Apply Loki LoadBalancer Service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k8s_namespace | default('default') }}"
    template:
      path: k8s/service-loadbalancer.yaml.j2
  when: loki_k8s_loadbalancer_expose_port

- name: Transfer Loki configuration
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loki
    tasks_from: k8s/config/transfer

- name: Apply Loki K8s crypto Secret
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loki
    tasks_from: k8s/crypto/transfer
  when: loki_use_tls

- name: Deploy Loki StatefulSet
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k8s_namespace | default('default') }}"
    template:
      path: k8s/statefulset.yaml.j2
    wait: true
    wait_timeout: "{{ loki_k8s_wait_timeout }}"
