#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Namespace
# =========================
- name: Ensure Kubernetes namespace exists for Fabric-X Loadgen
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: namespace/create

# =========================
# Resolve dynamic cert paths via glob
# =========================
- name: Resolve Fabric-X Loadgen MSP CA cert path for Fabric CA
  ansible.builtin.set_fact:
    loadgen_k8s_msp_cacert_path: >-
      {{
        query('fileglob', loadgen_remote_config_dir + '/msp/cacerts/*.pem')
        | first
      }}
  when:
    - organization.fabric_ca_host is defined

- name: Resolve Fabric-X Loadgen MSP CA cert path for cryptogen
  ansible.builtin.set_fact:
    loadgen_k8s_msp_cacert_path: "{{ loadgen_remote_config_dir }}/msp/cacerts/ca.{{ organization.domain }}-cert.pem"
  when:
    - organization.fabric_ca_host is undefined

# =========================
# Apply Secret
# =========================
- name: Apply Fabric-X Loadgen Secret
  vars:
    cryptogen_signcert_file: "{{ loadgen_crypto_name }}.{{ organization.domain }}-cert.pem"
    fabric_ca_signcert_file: "cert.pem"
    signcert_file: >-
      {{
        cryptogen_signcert_file
        if organization.fabric_ca_host is undefined
        else fabric_ca_signcert_file
      }}
    loadgen_k8s_msp_keystore_path: "{{ loadgen_remote_config_dir }}/msp/keystore/priv_sk"
    loadgen_k8s_msp_signcert_path: "{{ loadgen_remote_config_dir }}/msp/signcerts/{{ signcert_file }}"
    loadgen_k8s_msp_config_path: "{{ loadgen_remote_config_dir }}/msp/config.yaml"
    loadgen_k8s_tls_server_key_path: "{{ loadgen_remote_config_dir }}/tls/server.key"
    loadgen_k8s_tls_server_crt_path: "{{ loadgen_remote_config_dir }}/tls/server.crt"
    loadgen_k8s_tls_ca_crt_path: "{{ loadgen_remote_config_dir }}/tls/ca.crt"
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/secret.yaml.j2
