#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Jaeger ui OpenShift Route
  vars:
    openshift_route_name: "{{ jaeger_k8s_resource_name }}-ui"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: jaeger_openshift_ui_route is defined

- name: Delete Jaeger admin OpenShift Route
  vars:
    openshift_route_name: "{{ jaeger_k8s_resource_name }}-admin"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: jaeger_openshift_admin_route is defined

- name: Delete Jaeger http-server OpenShift Route
  vars:
    openshift_route_name: "{{ jaeger_k8s_resource_name }}-http-server"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: jaeger_openshift_http_server_route is defined

- name: Delete Jaeger http-collector OpenShift Route
  vars:
    openshift_route_name: "{{ jaeger_k8s_resource_name }}-http-collector"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: jaeger_openshift_http_collector_route is defined

- name: Delete Jaeger grpc-server OpenShift Route
  vars:
    openshift_route_name: "{{ jaeger_k8s_resource_name }}-grpc-server"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: jaeger_openshift_grpc_server_route is defined

- name: Delete Jaeger collector OpenShift Route
  vars:
    openshift_route_name: "{{ jaeger_k8s_resource_name }}-collector"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openshift
    tasks_from: route/rm
  when: jaeger_openshift_collector_route is defined

- name: Remove Jaeger workload using generic k8s flow
  ansible.builtin.include_role:
    name: hyperledger.fabricx.jaeger
    tasks_from: k8s/rm
