#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Postgres image
# =========================
postgres_registry_endpoint: "{{ lookup('env', 'POSTGRES_REGISTRY_ENDPOINT') or 'docker.io/library' }}"
postgres_image_name: postgres
postgres_image_tag: "16.4"
postgres_image: "{{ postgres_registry_endpoint }}/{{ postgres_image_name }}:{{ postgres_image_tag }}"
postgres_container_name: "{{ inventory_hostname }}"

# =========================
# Paths/Locations
# =========================
postgres_remote_config_dir: "{{ remote_config_dir }}"
postgres_remote_data_dir: "{{ remote_data_dir }}"
postgres_container_config_dir: /var/lib/postgresql/config
postgres_container_data_dir: /var/lib/postgresql/data

# =========================
# TLS settings
# =========================
postgres_use_tls: false
postgres_use_mtls: false

# =========================
# Deployment mode
# =========================
postgres_use_k8s: false
postgres_use_container: "{{ not postgres_use_k8s }}"

# =========================
# Kubernetes
# =========================
postgres_k8s_resource_name: "{{ inventory_hostname }}"
postgres_k8s_wait_timeout: 120
postgres_k8s_fs_group: 999
postgres_k8s_use_node_port: false

# =========================
# Miscellaneous
# =========================
postgres_tls_private_key_file: server.key
postgres_tls_cert_file: server.crt
