#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check that the fxconfig instances have been defined
  ansible.builtin.fail:
    msg: "No fxconfig host is indicated. Set it via 'fxconfig_service_instances'."
  when: fxconfig_service_instances is not defined

- name: Build {{ fxconfig_bin_name }}
  vars:
    # Git vars
    git_uri: "{{ fxconfig_git_uri }}"
    git_commit: "{{ fxconfig_git_commit }}"
    # Bin vars
    bin_name: "{{ fxconfig_bin_name }}"
    bin_service_instances: "{{ fxconfig_service_instances }}"
    # Go vars
    go_source_code_package: "{{ fxconfig_source_code_package }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: go/multiplatform_build
