#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Namespace
# =========================
- name: Ensure Kubernetes namespace exists for Fabric-X Committer query-service
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: namespace/create

# =========================
# mTLS client/org cert lists
# =========================
- name: Prepare mTLS cert lists for Fabric-X Committer query-service
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/config/mtls/transfer
  when: committer_use_mtls

# =========================
# Apply ConfigMap
# =========================
- name: Apply Fabric-X Committer query-service ConfigMap
  vars:
    committer_k8s_config_content: "{{ lookup('template', 'config-query-service.yaml.j2') }}"
    committer_k8s_db_ca_path: "{{ fetched_artifacts_dir }}/{{ postgres_db_host }}/tls/ca.crt"
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/configmap-query-service.yaml.j2
