#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Block Explorer container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.block_explorer
    tasks_from: container/stop
  when: block_explorer_use_container
