#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown AWX instance
  hosts: "{{ target_hosts | default('awx') }}:&awx"
  tasks:
    - name: Teardown AWX
      ansible.builtin.include_role:
        name: hyperledger.fabricx.awx
        tasks_from: teardown
