#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Compute the Fabric-X ConfigUpdate with the fxadmin binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxadmin
    tasks_from: bin/compute_update
  when:
    - fxadmin_use_bin

- name: Compute the Fabric-X ConfigUpdate with the fxadmin container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxadmin
    tasks_from: container/compute_update
  when:
    - not fxadmin_use_bin
