#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Decode the Fabric-X channel configuration block with the fxadmin binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxadmin
    tasks_from: bin/decode
  when:
    - fxadmin_use_bin

- name: Decode the Fabric-X channel configuration block with the fxadmin container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxadmin
    tasks_from: container/decode
  when:
    - not fxadmin_use_bin
