#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Setup the crypto material for the Fabric-X EVM gateway
  hosts: "{{ target_hosts | default('fabric_x_evm') }}:&fabric_x_evm"
  tasks:
    - name: Setup the crypto material for the Fabric-X EVM gateway
      ansible.builtin.include_role:
        name: hyperledger.fabricx.evm
        tasks_from: crypto/setup
    - name: Fetch Fabric-X EVM certificates
      ansible.builtin.include_role:
        name: hyperledger.fabricx.evm
        tasks_from: crypto/fetch
