#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =======================
# bin / container
# =======================
- name: Check that the DB port is open
  vars:
    utils_ports_to_ping:
      - "{{ postgres_port }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.utils
    tasks_from: ping
  when: not postgres_use_k8s

# =======================
# k8s / openshift
# =======================
- name: Check that the node ports are open
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres
    tasks_from: k8s/ping
  when: postgres_use_k8s or postgres_use_openshift

# =======================
# openshift
# =======================
- name: Check that the OpenShift Route is reachable
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres
    tasks_from: openshift/ping
  when: postgres_use_openshift

# =======================
# Postgres Exporter
# =======================
- name: Check that the Exporter port is open
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres_exporter
    tasks_from: ping
  when:
    - postgres_exporter_port is defined
