#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create list of machines to log into Container Registry
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Set the group "machines"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.utils
        tasks_from: select_one_host_per_machine

- name: Log into Container Registry
  hosts: "{{ target_hosts | default('machines') }}:&machines"
  vars:
    container_registry: "{{ registry_url }}"
    container_registry_username: "{{ registry_username }}"
    container_registry_password: "{{ registry_password }}"
  tasks:
    - name: Login the container engine in a container registry
      ansible.builtin.include_role:
        name: hyperledger.fabricx.container
        tasks_from: registry/login

- name: Select one host per k8s namespace for imagePullSecret creation
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Set the group "k8s_namespaces"
      ansible.builtin.include_role:
        name: hyperledger.fabricx.utils
        tasks_from: select_one_host_per_k8s_namespace

- name: Create imagePullSecret in Kubernetes clusters
  hosts: "{{ target_hosts | default('k8s_namespaces') }}:&k8s_namespaces"
  vars:
    k8s_registry_url: "{{ registry_url }}"
    k8s_registry_username: "{{ registry_username }}"
    k8s_registry_password: "{{ registry_password }}"
  tasks:
    - name: Create imagePullSecret in Kubernetes cluster
      ansible.builtin.include_role:
        name: hyperledger.fabricx.k8s
        tasks_from: registry/create_pull_secret
