#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete Block Explorer Kubernetes ConfigMap
  ansible.builtin.include_role:
    name: hyperledger.fabricx.block_explorer
    tasks_from: k8s/config/rm
  when: block_explorer_use_k8s or block_explorer_use_openshift

- name: Remove Block Explorer config directory
  ansible.builtin.file:
    path: "{{ block_explorer_remote_config_dir }}"
    state: absent
