#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Define fxadmin output directory
  ansible.builtin.set_fact:
    fxadmin_output_dir: "{{ fxadmin_output | dirname }}"

- name: Ensure fxadmin output directory exists
  ansible.builtin.file:
    path: "{{ fxadmin_output_dir }}"
    state: directory
    mode: "0o755"

- name: Transfer the ConfigUpdate to endorse
  ansible.builtin.copy:
    src: "{{ fxadmin_config_update }}"
    dest: "{{ fxadmin_output_dir }}/config_update.pb"
    mode: preserve

- name: Endorse the Fabric-X ConfigUpdate
  vars:
    container_name: "{{ fxadmin_container_name }}-tx-endorse"
    container_image: "{{ fxadmin_image }}"
    container_command: >-
      {{ fxadmin_bin_name }} tx
      endorse
      /tmp/config_update.pb
      --config={{ fxadmin_container_config_dir }}/{{ fxadmin_config_file }}
      --output=/tmp/{{ fxadmin_output | basename }}
    container_volumes:
      - "{{ fxadmin_remote_config_dir }}:{{ fxadmin_container_config_dir }}:z,ro"
      - "{{ fxadmin_output_dir }}:/tmp:z"
    container_run_detach_mode: false
    container_run_as_host_user: true
    container_autoremove: true
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start

- name: Fetch the endorsement
  ansible.builtin.fetch:
    src: "{{ fxadmin_output }}"
    dest: "{{ fxadmin_endorsements_dir }}/{{ fxadmin_output | basename }}"
    flat: true
    mode: preserve
