#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Namespace
# =========================
- name: Ensure Kubernetes namespace exists for Fabric CA
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: namespace/create

# =========================
# Apply Resources
# =========================
- name: Apply Fabric CA Service
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/service.yaml.j2

- name: Apply Fabric CA NodePort Service
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/service-nodeport.yaml.j2
  when: fabric_ca_server_k8s_use_node_port

- name: Apply Fabric CA Deployment
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/deployment.yaml.j2
    wait: true
    wait_timeout: "{{ fabric_ca_server_k8s_wait_timeout }}"
