#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Namespace
# =========================
- name: Ensure Kubernetes namespace exists for Fabric-X Committer validator
  ansible.builtin.include_role:
    name: hyperledger.fabricx.k8s
    tasks_from: namespace/create

# =========================
# Apply ConfigMap
# =========================
- name: Apply Fabric-X Committer validator ConfigMap
  vars:
    committer_k8s_db_ca_path: "{{ fetched_artifacts_dir }}/{{ postgres_db_host }}/tls/ca.crt"
  kubernetes.core.k8s:
    state: present
    template:
      path: k8s/configmap-validator.yaml.j2
