#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the logs from the Fabric-X Committer on Kubernetes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: k8s/fetch_logs
  when: committer_use_k8s or committer_use_openshift

- name: Fetch the logs from the Fabric-X Committer container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: container/fetch_logs
  when: committer_use_container

- name: Fetch the logs from the Fabric-X Committer binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: bin/fetch_logs
  when: committer_use_bin
