#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Initialize the committer database
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: "{{ committer_deployment_mode }}/init_db"
