#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Fabric-X Committer components
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: "{{ committer_deployment_mode }}/start"
  when:
    - committer_component_type is defined
