#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Committer components
  when:
    - committer_component_type is defined
  block:
    - name: Teardown Fabric-X Committer components as container or binary
      vars:
        committer_teardown_tasks:
          container: container/rm
          bin: bin/stop
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: "{{ committer_teardown_tasks[committer_deployment_mode] }}"
      when:
        - committer_deployment_mode in ['bin', 'container']
    - name: Teardown Fabric-X Committer components on Kubernetes or OpenShift
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: "{{ committer_component_type | replace('-', '_') }}/{{ committer_deployment_mode }}/rm"
      when:
        - committer_deployment_mode in ['k8s', 'openshift']
    - name: Remove Fabric-X Committer sidecar data
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: data/rm
      when:
        - committer_component_type == 'sidecar'
